/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief BabbleSim test entry point for the generated gatt_gen_notify profile.
 *
 *  Auto-generated by ble-gatt-generator; do not edit.
 */

#include "bstests.h"

extern struct bst_test_list *test_peripheral_install(struct bst_test_list *tests);
extern struct bst_test_list *test_central_install(struct bst_test_list *tests);

bst_test_install_t test_installers[] = {test_peripheral_install, test_central_install, NULL};

int main(void)
{
	bst_main();
	return 0;
}
