/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_secure GATT service implementation.
 *
 *  Auto-generated by gatt-gen; do not edit.
 */

#include <stdint.h>
#include <string.h>
#include <zephyr/toolchain.h>
#include <zephyr/sys/printk.h>
#include <zephyr/kernel.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>

#include "secure_svc_service.h"

/* Characteristic value buffers */
static uint8_t secure_svc_secret_value[16];

/* Thread-safe accessors */
K_MUTEX_DEFINE(secure_svc_secret_lock);

/* Characteristic presentation format and extended properties data */

/* secret accessors */
int secure_svc_secret_set(const uint8_t *data, uint16_t len)
{
	if (len > 16) {
		return -EINVAL;
	}

	k_mutex_lock(&secure_svc_secret_lock, K_FOREVER);
	memcpy(secure_svc_secret_value, data, len);
	k_mutex_unlock(&secure_svc_secret_lock);

	return 0;
}

int secure_svc_secret_get(uint8_t *data, uint16_t len)
{
	if (len > 16) {
		return -EINVAL;
	}

	k_mutex_lock(&secure_svc_secret_lock, K_FOREVER);
	memcpy(data, secure_svc_secret_value, len);
	k_mutex_unlock(&secure_svc_secret_lock);

	return 0;
}

/* Characteristic callbacks */
static ssize_t secure_svc_secret_read(struct bt_conn *conn,
						       const struct bt_gatt_attr *attr,
						       void *buf, uint16_t len, uint16_t offset)
{
	uint8_t *value = (uint8_t *)attr->user_data;
	ssize_t ret;

	k_mutex_lock(&secure_svc_secret_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, value, 16);
	k_mutex_unlock(&secure_svc_secret_lock);

	return ret;
}
static ssize_t secure_svc_secret_write(struct bt_conn *conn,
							const struct bt_gatt_attr *attr,
							const void *buf, uint16_t len,
							uint16_t offset, uint8_t flags)
{
	uint8_t *value = (uint8_t *)attr->user_data;

	if (offset + len > 16) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	k_mutex_lock(&secure_svc_secret_lock, K_FOREVER);
	memcpy(value + offset, buf, len);
	k_mutex_unlock(&secure_svc_secret_lock);

	return len;
}

/* Public API: push helpers */

/* Service declaration */
BT_GATT_SERVICE_DEFINE(secure_svc,
	BT_GATT_PRIMARY_SERVICE(BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef0))),
	BT_GATT_CHARACTERISTIC(BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef1)),
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ_ENCRYPT | BT_GATT_PERM_WRITE_ENCRYPT,
secure_svc_secret_read,
secure_svc_secret_write,
			       secure_svc_secret_value));
