/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_secure GATT service implementation (secure_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit. Put application logic in
 *  main.c or your own sources and call the public helpers declared in
 *  secure_svc_service.h.
 */

#include <errno.h>
#include <stdint.h>
#include <string.h>

#include <zephyr/kernel.h>
#include <zephyr/sys/printk.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>

#include "secure_svc_service.h"

/* ------------------------------------------------------------------------- */
/* Characteristic value storage                                              */
/* ------------------------------------------------------------------------- */

static uint8_t secure_svc_secret_value[SECURE_SVC_SECRET_SIZE];
static K_MUTEX_DEFINE(secure_svc_secret_lock);

/* ------------------------------------------------------------------------- */
/* Static descriptor payloads                                                */
/* ------------------------------------------------------------------------- */

/* ------------------------------------------------------------------------- */
/* Thread-safe accessors                                                     */
/* ------------------------------------------------------------------------- */

int secure_svc_secret_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(secure_svc_secret_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&secure_svc_secret_lock, K_FOREVER);
	memcpy(secure_svc_secret_value, data, len);
	k_mutex_unlock(&secure_svc_secret_lock);

	return 0;
}

int secure_svc_secret_get(uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(secure_svc_secret_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&secure_svc_secret_lock, K_FOREVER);
	memcpy(data, secure_svc_secret_value, len);
	k_mutex_unlock(&secure_svc_secret_lock);

	return 0;
}

/* ------------------------------------------------------------------------- */
/* GATT attribute callbacks                                                  */
/* ------------------------------------------------------------------------- */

static ssize_t secure_svc_secret_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				      void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	k_mutex_lock(&secure_svc_secret_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, secure_svc_secret_value,
				sizeof(secure_svc_secret_value));
	k_mutex_unlock(&secure_svc_secret_lock);

	return ret;
}

static ssize_t secure_svc_secret_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				       const void *buf, uint16_t len, uint16_t offset,
				       uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(secure_svc_secret_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&secure_svc_secret_lock, K_FOREVER);
	memcpy(secure_svc_secret_value + offset, buf, len);
	k_mutex_unlock(&secure_svc_secret_lock);

	secure_svc_secret_on_write(secure_svc_secret_value, sizeof(secure_svc_secret_value));

	return len;
}

/* ------------------------------------------------------------------------- */
/* Application hooks (weak defaults; override in your own sources)           */
/* ------------------------------------------------------------------------- */

__weak void secure_svc_secret_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

/* ------------------------------------------------------------------------- */
/* Push helpers                                                              */
/* ------------------------------------------------------------------------- */

/* ------------------------------------------------------------------------- */
/* Service declaration                                                       */
/* ------------------------------------------------------------------------- */

/* clang-format off */
BT_GATT_SERVICE_DEFINE(secure_svc,
	BT_GATT_PRIMARY_SERVICE(SECURE_SVC_UUID),

	/* secret: read, write */
	BT_GATT_CHARACTERISTIC(SECURE_SVC_SECRET_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ_ENCRYPT | BT_GATT_PERM_WRITE_ENCRYPT,
			       secure_svc_secret_read,
			       secure_svc_secret_write,
			       secure_svc_secret_value),
);
/* clang-format on */
