/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_secure GATT service definition.
 *
 *  Auto-generated by gatt-gen; do not edit.
 */

#ifndef ZEPHYR_GATT_GEN_SECURE_SVC_H_
#define ZEPHYR_GATT_GEN_SECURE_SVC_H_

#include <stdint.h>
#include <zephyr/bluetooth/gatt.h>

/** @brief Set the secret characteristic value.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed the value size.
 *
 *  @return 0 on success, or a negative error code on failure.
 */
int secure_svc_secret_set(const uint8_t *data, uint16_t len);

/** @brief Get the secret characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed the value size.
 *
 *  @return 0 on success, or a negative error code on failure.
 */
int secure_svc_secret_get(uint8_t *data, uint16_t len);

#endif /* ZEPHYR_GATT_GEN_SECURE_SVC_H_ */
