/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief BabbleSim central role for the gatt_gen_full self-test.
 *
 *  Scans for the peripheral, connects, discovers every generated
 *  characteristic by UUID, reads readable values, writes and reads back
 *  writable values, and subscribes to all notify/indicate characteristics.
 *
 *  Auto-generated by ble-gatt-generator; do not edit.
 */

#include <stddef.h>
#include <errno.h>
#include <string.h>

#include <zephyr/kernel.h>
#include <zephyr/types.h>
#include <zephyr/sys/util.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/conn.h>
#include <zephyr/bluetooth/uuid.h>
#include <zephyr/bluetooth/gatt.h>

#include "babblekit/testcase.h"
#include "babblekit/flags.h"
#include "babblekit/sync.h"

#include "props_svc_service.h"
#include "sec_svc_service.h"
#include "desc_svc_service.h"

/* Notifications the peripheral pushes per characteristic. */
#define NOTIFICATION_COUNT 5
/* How long to wait for asynchronous results, in poll iterations. */
#define WAIT_ITERS         500
/* Shared with the peripheral so passkey entry always matches. */
#define TEST_PASSKEY       123456

DEFINE_FLAG_STATIC(flag_is_connected);
DEFINE_FLAG_STATIC(flag_discover_done);
DEFINE_FLAG_STATIC(flag_read_done);
DEFINE_FLAG_STATIC(flag_write_done);
DEFINE_FLAG_STATIC(flag_is_encrypted);
DEFINE_FLAG_STATIC(props_svc_notify_only_subscribed);
DEFINE_FLAG_STATIC(props_svc_indicate_only_subscribed);
DEFINE_FLAG_STATIC(props_svc_read_notify_subscribed);
DEFINE_FLAG_STATIC(props_svc_read_indicate_subscribed);
DEFINE_FLAG_STATIC(props_svc_rw_notify_subscribed);
DEFINE_FLAG_STATIC(props_svc_rw_indicate_subscribed);
DEFINE_FLAG_STATIC(props_svc_wwr_notify_subscribed);
DEFINE_FLAG_STATIC(sec_svc_enc_notify_subscribed);
DEFINE_FLAG_STATIC(sec_svc_auth_indicate_subscribed);
DEFINE_FLAG_STATIC(desc_svc_described_subscribed);

static struct bt_conn *g_conn;

/* ------------------------------------------------------------------ */
/* Connection handling                                                 */
/* ------------------------------------------------------------------ */

static void connected(struct bt_conn *conn, uint8_t err)
{
	char addr[BT_ADDR_LE_STR_LEN];

	bt_addr_le_to_str(bt_conn_get_dst(conn), addr, sizeof(addr));

	if (err != 0) {
		TEST_FAIL("Failed to connect to %s (%u)", addr, err);
		return;
	}

	printk("Connected to %s\n", addr);
	SET_FLAG(flag_is_connected);
}

static void disconnected(struct bt_conn *conn, uint8_t reason)
{
	char addr[BT_ADDR_LE_STR_LEN];

	if (conn != g_conn) {
		return;
	}

	bt_addr_le_to_str(bt_conn_get_dst(conn), addr, sizeof(addr));

	printk("Disconnected: %s (reason 0x%02x)\n", addr, reason);

	bt_conn_unref(g_conn);
	g_conn = NULL;
	UNSET_FLAG(flag_is_connected);
}

static void security_changed(struct bt_conn *conn, bt_security_t level, enum bt_security_err err)
{
	ARG_UNUSED(conn);

	if (err) {
		TEST_FAIL("Encryption failure (%d)", err);
	} else if (level < BT_SECURITY_L4) {
		TEST_FAIL("Insufficient security level (%d)", level);
	} else {
		SET_FLAG(flag_is_encrypted);
	}
}
/* Pairing callbacks that answer every method deterministically. The
 * peripheral side uses the same fixed passkey, so passkey entry always
 * matches and numeric comparison is simply confirmed.
 */
static void auth_passkey_display(struct bt_conn *conn, unsigned int passkey)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(passkey);
}

static void auth_passkey_entry(struct bt_conn *conn)
{
	int err = bt_conn_auth_passkey_entry(conn, TEST_PASSKEY);

	if (err) {
		TEST_FAIL("Passkey entry failed (err %d)", err);
	}
}

static void auth_passkey_confirm(struct bt_conn *conn, unsigned int passkey)
{
	ARG_UNUSED(passkey);

	int err = bt_conn_auth_passkey_confirm(conn);

	if (err) {
		TEST_FAIL("Passkey confirm failed (err %d)", err);
	}
}

static void auth_pairing_confirm(struct bt_conn *conn)
{
	int err = bt_conn_auth_pairing_confirm(conn);

	if (err) {
		TEST_FAIL("Pairing confirm failed (err %d)", err);
	}
}

static void auth_cancel(struct bt_conn *conn)
{
	ARG_UNUSED(conn);
}

static struct bt_conn_auth_cb auth_callbacks = {
	.passkey_display = auth_passkey_display,
	.passkey_entry = auth_passkey_entry,
	.passkey_confirm = auth_passkey_confirm,
	.pairing_confirm = auth_pairing_confirm,
	.cancel = auth_cancel,
};

BT_CONN_CB_DEFINE(conn_callbacks) = {
	.connected = connected,
	.disconnected = disconnected,
	.security_changed = security_changed,
};

static void device_found(const bt_addr_le_t *addr, int8_t rssi, uint8_t type,
			 struct net_buf_simple *ad)
{
	char addr_str[BT_ADDR_LE_STR_LEN];
	int err;

	if (g_conn != NULL) {
		return;
	}

	/* Only interested in connectable advertising. */
	if (type != BT_HCI_ADV_IND && type != BT_HCI_ADV_DIRECT_IND) {
		return;
	}

	bt_addr_le_to_str(addr, addr_str, sizeof(addr_str));
	printk("Device found: %s (RSSI %d)\n", addr_str, rssi);

	err = bt_le_scan_stop();
	if (err != 0) {
		TEST_FAIL("Could not stop scan: %d", err);
		return;
	}

	err = bt_conn_le_create(addr, BT_CONN_LE_CREATE_CONN, BT_LE_CONN_PARAM_DEFAULT, &g_conn);
	if (err != 0) {
		TEST_FAIL("Could not connect to peer: %d", err);
	}
}

/* ------------------------------------------------------------------ */
/* Discovery                                                           */
/* ------------------------------------------------------------------ */

static struct bt_gatt_discover_params disc_params;
static uint16_t *disc_handle_out;

static uint8_t discover_func(struct bt_conn *conn, const struct bt_gatt_attr *attr,
			     struct bt_gatt_discover_params *params)
{
	ARG_UNUSED(conn);

	if (attr == NULL) {
		(void)memset(params, 0, sizeof(*params));
		SET_FLAG(flag_discover_done);
		return BT_GATT_ITER_STOP;
	}

	if (params->type == BT_GATT_DISCOVER_CHARACTERISTIC) {
		const struct bt_gatt_chrc *chrc = attr->user_data;

		*disc_handle_out = chrc->value_handle;
	}
	/* Stopping here aborts the procedure: no trailing attr == NULL
	 * callback follows, so flag completion right now.
	 */
	SET_FLAG(flag_discover_done);

	return BT_GATT_ITER_STOP;
}

static uint16_t discover_chrc(const struct bt_uuid *uuid)
{
	uint16_t handle = 0;
	int err;

	disc_handle_out = &handle;
	disc_params.uuid = uuid;
	disc_params.func = discover_func;
	disc_params.start_handle = BT_ATT_FIRST_ATTRIBUTE_HANDLE;
	disc_params.end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE;
	disc_params.type = BT_GATT_DISCOVER_CHARACTERISTIC;

	err = bt_gatt_discover(g_conn, &disc_params);
	if (err) {
		TEST_FAIL("Discover failed (err %d)", err);
	}

	WAIT_FOR_FLAG(flag_discover_done);
	UNSET_FLAG(flag_discover_done);

	return handle;
}

/* ------------------------------------------------------------------ */
/* Read and write helpers                                              */
/* ------------------------------------------------------------------ */

static struct bt_gatt_read_params read_params;
static uint8_t read_buf[512];
static uint16_t read_len;

static uint8_t read_func(struct bt_conn *conn, uint8_t err, struct bt_gatt_read_params *params,
			 const void *data, uint16_t length)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("Read failed (err 0x%02x)", err);
	}

	read_len = length;
	if (data != NULL && length > 0) {
		(void)memcpy(read_buf, data, MIN(length, sizeof(read_buf)));
	}
	SET_FLAG(flag_read_done);

	return BT_GATT_ITER_STOP;
}

static uint16_t read_chrc(uint16_t handle)
{
	int err;

	read_params.func = read_func;
	read_params.handle_count = 1;
	read_params.single.handle = handle;
	read_params.single.offset = 0;

	err = bt_gatt_read(g_conn, &read_params);
	if (err) {
		TEST_FAIL("Read request failed (err %d)", err);
	}

	WAIT_FOR_FLAG(flag_read_done);
	UNSET_FLAG(flag_read_done);

	return read_len;
}

static struct bt_gatt_write_params write_params;

static void write_func(struct bt_conn *conn, uint8_t err, struct bt_gatt_write_params *params)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("Write failed (err 0x%02x)", err);
	}
	SET_FLAG(flag_write_done);
}

static void write_chrc(uint16_t handle, const uint8_t *data, uint16_t len)
{
	int err;

	write_params.func = write_func;
	write_params.handle = handle;
	write_params.offset = 0;
	write_params.data = data;
	write_params.length = len;

	err = bt_gatt_write(g_conn, &write_params);
	if (err) {
		TEST_FAIL("Write request failed (err %d)", err);
	}

	WAIT_FOR_FLAG(flag_write_done);
	UNSET_FLAG(flag_write_done);
}

/* ------------------------------------------------------------------ */
/* Subscriptions                                                       */
/* ------------------------------------------------------------------ */

static volatile size_t props_svc_notify_only_received;

static uint8_t props_svc_notify_only_notify_cb(struct bt_conn *conn,
					       struct bt_gatt_subscribe_params *params,
					       const void *data, uint16_t length)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);
	ARG_UNUSED(data);

	props_svc_notify_only_received++;
	printk("props_svc/notify_only: received value #%u (len %u)\n",
	       props_svc_notify_only_received, length);

	return BT_GATT_ITER_CONTINUE;
}

static void props_svc_notify_only_subscribed_cb(struct bt_conn *conn, uint8_t err,
						struct bt_gatt_subscribe_params *params)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("props_svc/notify_only subscribe failed (err 0x%02x)", err);
	}

	SET_FLAG(props_svc_notify_only_subscribed);
}

static struct bt_gatt_discover_params props_svc_notify_only_ccc_disc;
static struct bt_gatt_subscribe_params props_svc_notify_only_sub = {
	.notify = props_svc_notify_only_notify_cb,
	.subscribe = props_svc_notify_only_subscribed_cb,
	.ccc_handle = BT_GATT_AUTO_DISCOVER_CCC_HANDLE,
	.disc_params = &props_svc_notify_only_ccc_disc,
	.end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE,
	.value = BT_GATT_CCC_NOTIFY,
	.min_security = BT_SECURITY_L4,
};

static volatile size_t props_svc_indicate_only_received;

static uint8_t props_svc_indicate_only_notify_cb(struct bt_conn *conn,
						 struct bt_gatt_subscribe_params *params,
						 const void *data, uint16_t length)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);
	ARG_UNUSED(data);

	props_svc_indicate_only_received++;
	printk("props_svc/indicate_only: received value #%u (len %u)\n",
	       props_svc_indicate_only_received, length);

	return BT_GATT_ITER_CONTINUE;
}

static void props_svc_indicate_only_subscribed_cb(struct bt_conn *conn, uint8_t err,
						  struct bt_gatt_subscribe_params *params)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("props_svc/indicate_only subscribe failed (err 0x%02x)", err);
	}

	SET_FLAG(props_svc_indicate_only_subscribed);
}

static struct bt_gatt_discover_params props_svc_indicate_only_ccc_disc;
static struct bt_gatt_subscribe_params props_svc_indicate_only_sub = {
	.notify = props_svc_indicate_only_notify_cb,
	.subscribe = props_svc_indicate_only_subscribed_cb,
	.ccc_handle = BT_GATT_AUTO_DISCOVER_CCC_HANDLE,
	.disc_params = &props_svc_indicate_only_ccc_disc,
	.end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE,
	.value = BT_GATT_CCC_INDICATE,
	.min_security = BT_SECURITY_L4,
};

static volatile size_t props_svc_read_notify_received;

static uint8_t props_svc_read_notify_notify_cb(struct bt_conn *conn,
					       struct bt_gatt_subscribe_params *params,
					       const void *data, uint16_t length)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);
	ARG_UNUSED(data);

	props_svc_read_notify_received++;
	printk("props_svc/read_notify: received value #%u (len %u)\n",
	       props_svc_read_notify_received, length);

	return BT_GATT_ITER_CONTINUE;
}

static void props_svc_read_notify_subscribed_cb(struct bt_conn *conn, uint8_t err,
						struct bt_gatt_subscribe_params *params)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("props_svc/read_notify subscribe failed (err 0x%02x)", err);
	}

	SET_FLAG(props_svc_read_notify_subscribed);
}

static struct bt_gatt_discover_params props_svc_read_notify_ccc_disc;
static struct bt_gatt_subscribe_params props_svc_read_notify_sub = {
	.notify = props_svc_read_notify_notify_cb,
	.subscribe = props_svc_read_notify_subscribed_cb,
	.ccc_handle = BT_GATT_AUTO_DISCOVER_CCC_HANDLE,
	.disc_params = &props_svc_read_notify_ccc_disc,
	.end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE,
	.value = BT_GATT_CCC_NOTIFY,
	.min_security = BT_SECURITY_L4,
};

static volatile size_t props_svc_read_indicate_received;

static uint8_t props_svc_read_indicate_notify_cb(struct bt_conn *conn,
						 struct bt_gatt_subscribe_params *params,
						 const void *data, uint16_t length)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);
	ARG_UNUSED(data);

	props_svc_read_indicate_received++;
	printk("props_svc/read_indicate: received value #%u (len %u)\n",
	       props_svc_read_indicate_received, length);

	return BT_GATT_ITER_CONTINUE;
}

static void props_svc_read_indicate_subscribed_cb(struct bt_conn *conn, uint8_t err,
						  struct bt_gatt_subscribe_params *params)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("props_svc/read_indicate subscribe failed (err 0x%02x)", err);
	}

	SET_FLAG(props_svc_read_indicate_subscribed);
}

static struct bt_gatt_discover_params props_svc_read_indicate_ccc_disc;
static struct bt_gatt_subscribe_params props_svc_read_indicate_sub = {
	.notify = props_svc_read_indicate_notify_cb,
	.subscribe = props_svc_read_indicate_subscribed_cb,
	.ccc_handle = BT_GATT_AUTO_DISCOVER_CCC_HANDLE,
	.disc_params = &props_svc_read_indicate_ccc_disc,
	.end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE,
	.value = BT_GATT_CCC_INDICATE,
	.min_security = BT_SECURITY_L4,
};

static volatile size_t props_svc_rw_notify_received;

static uint8_t props_svc_rw_notify_notify_cb(struct bt_conn *conn,
					     struct bt_gatt_subscribe_params *params,
					     const void *data, uint16_t length)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);
	ARG_UNUSED(data);

	props_svc_rw_notify_received++;
	printk("props_svc/rw_notify: received value #%u (len %u)\n", props_svc_rw_notify_received,
	       length);

	return BT_GATT_ITER_CONTINUE;
}

static void props_svc_rw_notify_subscribed_cb(struct bt_conn *conn, uint8_t err,
					      struct bt_gatt_subscribe_params *params)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("props_svc/rw_notify subscribe failed (err 0x%02x)", err);
	}

	SET_FLAG(props_svc_rw_notify_subscribed);
}

static struct bt_gatt_discover_params props_svc_rw_notify_ccc_disc;
static struct bt_gatt_subscribe_params props_svc_rw_notify_sub = {
	.notify = props_svc_rw_notify_notify_cb,
	.subscribe = props_svc_rw_notify_subscribed_cb,
	.ccc_handle = BT_GATT_AUTO_DISCOVER_CCC_HANDLE,
	.disc_params = &props_svc_rw_notify_ccc_disc,
	.end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE,
	.value = BT_GATT_CCC_NOTIFY,
	.min_security = BT_SECURITY_L4,
};

static volatile size_t props_svc_rw_indicate_received;

static uint8_t props_svc_rw_indicate_notify_cb(struct bt_conn *conn,
					       struct bt_gatt_subscribe_params *params,
					       const void *data, uint16_t length)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);
	ARG_UNUSED(data);

	props_svc_rw_indicate_received++;
	printk("props_svc/rw_indicate: received value #%u (len %u)\n",
	       props_svc_rw_indicate_received, length);

	return BT_GATT_ITER_CONTINUE;
}

static void props_svc_rw_indicate_subscribed_cb(struct bt_conn *conn, uint8_t err,
						struct bt_gatt_subscribe_params *params)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("props_svc/rw_indicate subscribe failed (err 0x%02x)", err);
	}

	SET_FLAG(props_svc_rw_indicate_subscribed);
}

static struct bt_gatt_discover_params props_svc_rw_indicate_ccc_disc;
static struct bt_gatt_subscribe_params props_svc_rw_indicate_sub = {
	.notify = props_svc_rw_indicate_notify_cb,
	.subscribe = props_svc_rw_indicate_subscribed_cb,
	.ccc_handle = BT_GATT_AUTO_DISCOVER_CCC_HANDLE,
	.disc_params = &props_svc_rw_indicate_ccc_disc,
	.end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE,
	.value = BT_GATT_CCC_INDICATE,
	.min_security = BT_SECURITY_L4,
};

static volatile size_t props_svc_wwr_notify_received;

static uint8_t props_svc_wwr_notify_notify_cb(struct bt_conn *conn,
					      struct bt_gatt_subscribe_params *params,
					      const void *data, uint16_t length)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);
	ARG_UNUSED(data);

	props_svc_wwr_notify_received++;
	printk("props_svc/wwr_notify: received value #%u (len %u)\n", props_svc_wwr_notify_received,
	       length);

	return BT_GATT_ITER_CONTINUE;
}

static void props_svc_wwr_notify_subscribed_cb(struct bt_conn *conn, uint8_t err,
					       struct bt_gatt_subscribe_params *params)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("props_svc/wwr_notify subscribe failed (err 0x%02x)", err);
	}

	SET_FLAG(props_svc_wwr_notify_subscribed);
}

static struct bt_gatt_discover_params props_svc_wwr_notify_ccc_disc;
static struct bt_gatt_subscribe_params props_svc_wwr_notify_sub = {
	.notify = props_svc_wwr_notify_notify_cb,
	.subscribe = props_svc_wwr_notify_subscribed_cb,
	.ccc_handle = BT_GATT_AUTO_DISCOVER_CCC_HANDLE,
	.disc_params = &props_svc_wwr_notify_ccc_disc,
	.end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE,
	.value = BT_GATT_CCC_NOTIFY,
	.min_security = BT_SECURITY_L4,
};

static volatile size_t sec_svc_enc_notify_received;

static uint8_t sec_svc_enc_notify_notify_cb(struct bt_conn *conn,
					    struct bt_gatt_subscribe_params *params,
					    const void *data, uint16_t length)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);
	ARG_UNUSED(data);

	sec_svc_enc_notify_received++;
	printk("sec_svc/enc_notify: received value #%u (len %u)\n", sec_svc_enc_notify_received,
	       length);

	return BT_GATT_ITER_CONTINUE;
}

static void sec_svc_enc_notify_subscribed_cb(struct bt_conn *conn, uint8_t err,
					     struct bt_gatt_subscribe_params *params)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("sec_svc/enc_notify subscribe failed (err 0x%02x)", err);
	}

	SET_FLAG(sec_svc_enc_notify_subscribed);
}

static struct bt_gatt_discover_params sec_svc_enc_notify_ccc_disc;
static struct bt_gatt_subscribe_params sec_svc_enc_notify_sub = {
	.notify = sec_svc_enc_notify_notify_cb,
	.subscribe = sec_svc_enc_notify_subscribed_cb,
	.ccc_handle = BT_GATT_AUTO_DISCOVER_CCC_HANDLE,
	.disc_params = &sec_svc_enc_notify_ccc_disc,
	.end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE,
	.value = BT_GATT_CCC_NOTIFY,
	.min_security = BT_SECURITY_L4,
};

static volatile size_t sec_svc_auth_indicate_received;

static uint8_t sec_svc_auth_indicate_notify_cb(struct bt_conn *conn,
					       struct bt_gatt_subscribe_params *params,
					       const void *data, uint16_t length)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);
	ARG_UNUSED(data);

	sec_svc_auth_indicate_received++;
	printk("sec_svc/auth_indicate: received value #%u (len %u)\n",
	       sec_svc_auth_indicate_received, length);

	return BT_GATT_ITER_CONTINUE;
}

static void sec_svc_auth_indicate_subscribed_cb(struct bt_conn *conn, uint8_t err,
						struct bt_gatt_subscribe_params *params)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("sec_svc/auth_indicate subscribe failed (err 0x%02x)", err);
	}

	SET_FLAG(sec_svc_auth_indicate_subscribed);
}

static struct bt_gatt_discover_params sec_svc_auth_indicate_ccc_disc;
static struct bt_gatt_subscribe_params sec_svc_auth_indicate_sub = {
	.notify = sec_svc_auth_indicate_notify_cb,
	.subscribe = sec_svc_auth_indicate_subscribed_cb,
	.ccc_handle = BT_GATT_AUTO_DISCOVER_CCC_HANDLE,
	.disc_params = &sec_svc_auth_indicate_ccc_disc,
	.end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE,
	.value = BT_GATT_CCC_INDICATE,
	.min_security = BT_SECURITY_L4,
};

static volatile size_t desc_svc_described_received;

static uint8_t desc_svc_described_notify_cb(struct bt_conn *conn,
					    struct bt_gatt_subscribe_params *params,
					    const void *data, uint16_t length)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);
	ARG_UNUSED(data);

	desc_svc_described_received++;
	printk("desc_svc/described: received value #%u (len %u)\n", desc_svc_described_received,
	       length);

	return BT_GATT_ITER_CONTINUE;
}

static void desc_svc_described_subscribed_cb(struct bt_conn *conn, uint8_t err,
					     struct bt_gatt_subscribe_params *params)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(params);

	if (err) {
		TEST_FAIL("desc_svc/described subscribe failed (err 0x%02x)", err);
	}

	SET_FLAG(desc_svc_described_subscribed);
}

static struct bt_gatt_discover_params desc_svc_described_ccc_disc;
static struct bt_gatt_subscribe_params desc_svc_described_sub = {
	.notify = desc_svc_described_notify_cb,
	.subscribe = desc_svc_described_subscribed_cb,
	.ccc_handle = BT_GATT_AUTO_DISCOVER_CCC_HANDLE,
	.disc_params = &desc_svc_described_ccc_disc,
	.end_handle = BT_ATT_LAST_ATTRIBUTE_HANDLE,
	.value = BT_GATT_CCC_NOTIFY,
	.min_security = BT_SECURITY_L4,
};

/* ------------------------------------------------------------------ */
/* Test                                                                */
/* ------------------------------------------------------------------ */

static void test_central(void)
{
	int err;

	err = bk_sync_init();
	if (err) {
		TEST_FAIL("Backchannel init failed (err %d)", err);
	}

	/* Match the fixed passkey used on the peripheral side. */
	err = bt_passkey_set(TEST_PASSKEY);
	if (err) {
		TEST_FAIL("bt_passkey_set failed (err %d)", err);
	}

	err = bt_conn_auth_cb_register(&auth_callbacks);
	if (err) {
		TEST_FAIL("Auth callback register failed (err %d)", err);
	}

	err = bt_enable(NULL);
	if (err != 0) {
		TEST_FAIL("Bluetooth init failed (err %d)", err);
	}

	err = bt_le_scan_start(BT_LE_SCAN_PASSIVE, device_found);
	if (err != 0) {
		TEST_FAIL("Scanning failed to start (err %d)", err);
	}

	printk("Scanning successfully started\n");

	WAIT_FOR_FLAG(flag_is_connected);

	/* Single ATT reads/writes are limited by the negotiated MTU. */
	const uint16_t att_mtu = bt_gatt_get_mtu(g_conn);

	err = bt_conn_set_security(g_conn, BT_SECURITY_L4);
	if (err) {
		TEST_FAIL("Starting security procedure failed (%d)", err);
	}
	WAIT_FOR_FLAG(flag_is_encrypted);
	printk("Link encrypted\n");

	/* Discover every generated characteristic by UUID. */
	uint16_t props_svc_read_only_handle = discover_chrc(PROPS_SVC_READ_ONLY_UUID);
	if (props_svc_read_only_handle == 0) {
		TEST_FAIL("props_svc/read_only not found");
	}
	printk("props_svc/read_only: value handle %u\n", props_svc_read_only_handle);
	uint16_t props_svc_write_only_handle = discover_chrc(PROPS_SVC_WRITE_ONLY_UUID);
	if (props_svc_write_only_handle == 0) {
		TEST_FAIL("props_svc/write_only not found");
	}
	printk("props_svc/write_only: value handle %u\n", props_svc_write_only_handle);
	uint16_t props_svc_wwr_only_handle = discover_chrc(PROPS_SVC_WWR_ONLY_UUID);
	if (props_svc_wwr_only_handle == 0) {
		TEST_FAIL("props_svc/wwr_only not found");
	}
	printk("props_svc/wwr_only: value handle %u\n", props_svc_wwr_only_handle);
	uint16_t props_svc_read_write_handle = discover_chrc(PROPS_SVC_READ_WRITE_UUID);
	if (props_svc_read_write_handle == 0) {
		TEST_FAIL("props_svc/read_write not found");
	}
	printk("props_svc/read_write: value handle %u\n", props_svc_read_write_handle);
	uint16_t props_svc_notify_only_handle = discover_chrc(PROPS_SVC_NOTIFY_ONLY_UUID);
	if (props_svc_notify_only_handle == 0) {
		TEST_FAIL("props_svc/notify_only not found");
	}
	printk("props_svc/notify_only: value handle %u\n", props_svc_notify_only_handle);
	uint16_t props_svc_indicate_only_handle = discover_chrc(PROPS_SVC_INDICATE_ONLY_UUID);
	if (props_svc_indicate_only_handle == 0) {
		TEST_FAIL("props_svc/indicate_only not found");
	}
	printk("props_svc/indicate_only: value handle %u\n", props_svc_indicate_only_handle);
	uint16_t props_svc_read_notify_handle = discover_chrc(PROPS_SVC_READ_NOTIFY_UUID);
	if (props_svc_read_notify_handle == 0) {
		TEST_FAIL("props_svc/read_notify not found");
	}
	printk("props_svc/read_notify: value handle %u\n", props_svc_read_notify_handle);
	uint16_t props_svc_read_indicate_handle = discover_chrc(PROPS_SVC_READ_INDICATE_UUID);
	if (props_svc_read_indicate_handle == 0) {
		TEST_FAIL("props_svc/read_indicate not found");
	}
	printk("props_svc/read_indicate: value handle %u\n", props_svc_read_indicate_handle);
	uint16_t props_svc_rw_notify_handle = discover_chrc(PROPS_SVC_RW_NOTIFY_UUID);
	if (props_svc_rw_notify_handle == 0) {
		TEST_FAIL("props_svc/rw_notify not found");
	}
	printk("props_svc/rw_notify: value handle %u\n", props_svc_rw_notify_handle);
	uint16_t props_svc_rw_indicate_handle = discover_chrc(PROPS_SVC_RW_INDICATE_UUID);
	if (props_svc_rw_indicate_handle == 0) {
		TEST_FAIL("props_svc/rw_indicate not found");
	}
	printk("props_svc/rw_indicate: value handle %u\n", props_svc_rw_indicate_handle);
	uint16_t props_svc_wwr_notify_handle = discover_chrc(PROPS_SVC_WWR_NOTIFY_UUID);
	if (props_svc_wwr_notify_handle == 0) {
		TEST_FAIL("props_svc/wwr_notify not found");
	}
	printk("props_svc/wwr_notify: value handle %u\n", props_svc_wwr_notify_handle);
	uint16_t props_svc_broadcast_chrc_handle = discover_chrc(PROPS_SVC_BROADCAST_CHRC_UUID);
	if (props_svc_broadcast_chrc_handle == 0) {
		TEST_FAIL("props_svc/broadcast_chrc not found");
	}
	printk("props_svc/broadcast_chrc: value handle %u\n", props_svc_broadcast_chrc_handle);
	uint16_t props_svc_signed_rw_handle = discover_chrc(PROPS_SVC_SIGNED_RW_UUID);
	if (props_svc_signed_rw_handle == 0) {
		TEST_FAIL("props_svc/signed_rw not found");
	}
	printk("props_svc/signed_rw: value handle %u\n", props_svc_signed_rw_handle);
	uint16_t props_svc_ext_props_handle = discover_chrc(PROPS_SVC_EXT_PROPS_UUID);
	if (props_svc_ext_props_handle == 0) {
		TEST_FAIL("props_svc/ext_props not found");
	}
	printk("props_svc/ext_props: value handle %u\n", props_svc_ext_props_handle);
	uint16_t props_svc_big_value_handle = discover_chrc(PROPS_SVC_BIG_VALUE_UUID);
	if (props_svc_big_value_handle == 0) {
		TEST_FAIL("props_svc/big_value not found");
	}
	printk("props_svc/big_value: value handle %u\n", props_svc_big_value_handle);
	uint16_t sec_svc_enc_read_handle = discover_chrc(SEC_SVC_ENC_READ_UUID);
	if (sec_svc_enc_read_handle == 0) {
		TEST_FAIL("sec_svc/enc_read not found");
	}
	printk("sec_svc/enc_read: value handle %u\n", sec_svc_enc_read_handle);
	uint16_t sec_svc_enc_write_handle = discover_chrc(SEC_SVC_ENC_WRITE_UUID);
	if (sec_svc_enc_write_handle == 0) {
		TEST_FAIL("sec_svc/enc_write not found");
	}
	printk("sec_svc/enc_write: value handle %u\n", sec_svc_enc_write_handle);
	uint16_t sec_svc_enc_rw_handle = discover_chrc(SEC_SVC_ENC_RW_UUID);
	if (sec_svc_enc_rw_handle == 0) {
		TEST_FAIL("sec_svc/enc_rw not found");
	}
	printk("sec_svc/enc_rw: value handle %u\n", sec_svc_enc_rw_handle);
	uint16_t sec_svc_auth_read_handle = discover_chrc(SEC_SVC_AUTH_READ_UUID);
	if (sec_svc_auth_read_handle == 0) {
		TEST_FAIL("sec_svc/auth_read not found");
	}
	printk("sec_svc/auth_read: value handle %u\n", sec_svc_auth_read_handle);
	uint16_t sec_svc_auth_rw_handle = discover_chrc(SEC_SVC_AUTH_RW_UUID);
	if (sec_svc_auth_rw_handle == 0) {
		TEST_FAIL("sec_svc/auth_rw not found");
	}
	printk("sec_svc/auth_rw: value handle %u\n", sec_svc_auth_rw_handle);
	uint16_t sec_svc_lesc_rw_handle = discover_chrc(SEC_SVC_LESC_RW_UUID);
	if (sec_svc_lesc_rw_handle == 0) {
		TEST_FAIL("sec_svc/lesc_rw not found");
	}
	printk("sec_svc/lesc_rw: value handle %u\n", sec_svc_lesc_rw_handle);
	uint16_t sec_svc_enc_notify_handle = discover_chrc(SEC_SVC_ENC_NOTIFY_UUID);
	if (sec_svc_enc_notify_handle == 0) {
		TEST_FAIL("sec_svc/enc_notify not found");
	}
	printk("sec_svc/enc_notify: value handle %u\n", sec_svc_enc_notify_handle);
	uint16_t sec_svc_auth_indicate_handle = discover_chrc(SEC_SVC_AUTH_INDICATE_UUID);
	if (sec_svc_auth_indicate_handle == 0) {
		TEST_FAIL("sec_svc/auth_indicate not found");
	}
	printk("sec_svc/auth_indicate: value handle %u\n", sec_svc_auth_indicate_handle);
	uint16_t desc_svc_described_handle = discover_chrc(DESC_SVC_DESCRIBED_UUID);
	if (desc_svc_described_handle == 0) {
		TEST_FAIL("desc_svc/described not found");
	}
	printk("desc_svc/described: value handle %u\n", desc_svc_described_handle);
	uint16_t desc_svc_full_meta_handle = discover_chrc(DESC_SVC_FULL_META_UUID);
	if (desc_svc_full_meta_handle == 0) {
		TEST_FAIL("desc_svc/full_meta not found");
	}
	printk("desc_svc/full_meta: value handle %u\n", desc_svc_full_meta_handle);
	uint16_t desc_svc_plain_handle = discover_chrc(DESC_SVC_PLAIN_UUID);
	if (desc_svc_plain_handle == 0) {
		TEST_FAIL("desc_svc/plain not found");
	}
	printk("desc_svc/plain: value handle %u\n", desc_svc_plain_handle);

	/* Verify readable characteristics return the expected number of bytes.
	 * A single ATT read is capped at MTU-1, so larger values come back
	 * truncated at the first read.
	 */
	{
		uint16_t len = read_chrc(props_svc_read_only_handle);
		uint16_t expected = MIN(PROPS_SVC_READ_ONLY_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("props_svc/read_only read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(props_svc_read_write_handle);
		uint16_t expected = MIN(PROPS_SVC_READ_WRITE_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("props_svc/read_write read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(props_svc_read_notify_handle);
		uint16_t expected = MIN(PROPS_SVC_READ_NOTIFY_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("props_svc/read_notify read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(props_svc_read_indicate_handle);
		uint16_t expected = MIN(PROPS_SVC_READ_INDICATE_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("props_svc/read_indicate read len %u, expected %u", len,
				  expected);
		}
	}
	{
		uint16_t len = read_chrc(props_svc_rw_notify_handle);
		uint16_t expected = MIN(PROPS_SVC_RW_NOTIFY_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("props_svc/rw_notify read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(props_svc_rw_indicate_handle);
		uint16_t expected = MIN(PROPS_SVC_RW_INDICATE_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("props_svc/rw_indicate read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(props_svc_broadcast_chrc_handle);
		uint16_t expected = MIN(PROPS_SVC_BROADCAST_CHRC_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("props_svc/broadcast_chrc read len %u, expected %u", len,
				  expected);
		}
	}
	{
		uint16_t len = read_chrc(props_svc_signed_rw_handle);
		uint16_t expected = MIN(PROPS_SVC_SIGNED_RW_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("props_svc/signed_rw read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(props_svc_ext_props_handle);
		uint16_t expected = MIN(PROPS_SVC_EXT_PROPS_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("props_svc/ext_props read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(props_svc_big_value_handle);
		uint16_t expected = MIN(PROPS_SVC_BIG_VALUE_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("props_svc/big_value read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(sec_svc_enc_read_handle);
		uint16_t expected = MIN(SEC_SVC_ENC_READ_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("sec_svc/enc_read read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(sec_svc_enc_rw_handle);
		uint16_t expected = MIN(SEC_SVC_ENC_RW_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("sec_svc/enc_rw read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(sec_svc_auth_read_handle);
		uint16_t expected = MIN(SEC_SVC_AUTH_READ_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("sec_svc/auth_read read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(sec_svc_auth_rw_handle);
		uint16_t expected = MIN(SEC_SVC_AUTH_RW_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("sec_svc/auth_rw read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(sec_svc_lesc_rw_handle);
		uint16_t expected = MIN(SEC_SVC_LESC_RW_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("sec_svc/lesc_rw read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(sec_svc_enc_notify_handle);
		uint16_t expected = MIN(SEC_SVC_ENC_NOTIFY_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("sec_svc/enc_notify read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(sec_svc_auth_indicate_handle);
		uint16_t expected = MIN(SEC_SVC_AUTH_INDICATE_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("sec_svc/auth_indicate read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(desc_svc_described_handle);
		uint16_t expected = MIN(DESC_SVC_DESCRIBED_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("desc_svc/described read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(desc_svc_full_meta_handle);
		uint16_t expected = MIN(DESC_SVC_FULL_META_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("desc_svc/full_meta read len %u, expected %u", len, expected);
		}
	}
	{
		uint16_t len = read_chrc(desc_svc_plain_handle);
		uint16_t expected = MIN(DESC_SVC_PLAIN_SIZE, att_mtu - 1);

		if (len != expected) {
			TEST_FAIL("desc_svc/plain read len %u, expected %u", len, expected);
		}
	}

	/* Exercise writable characteristics; verify by read-back when possible. */
	{
		uint8_t pattern[PROPS_SVC_WRITE_ONLY_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(props_svc_write_only_handle, pattern, wlen);
	}
	{
		uint8_t pattern[PROPS_SVC_WWR_ONLY_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		err = bt_gatt_write_without_response(g_conn, props_svc_wwr_only_handle, pattern,
						     wlen, false);
		if (err < 0) {
			TEST_FAIL("props_svc/wwr_only write failed (err %d)", err);
		}
		/* Write without response is queued; give it time to land. */
		k_sleep(K_MSEC(100));
	}
	{
		uint8_t pattern[PROPS_SVC_READ_WRITE_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(props_svc_read_write_handle, pattern, wlen);
		{
			uint16_t len = read_chrc(props_svc_read_write_handle);

			if (len < wlen || memcmp(read_buf, pattern, wlen) != 0) {
				TEST_FAIL("props_svc/read_write read-back mismatch");
			}
		}
	}
	{
		uint8_t pattern[PROPS_SVC_RW_NOTIFY_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(props_svc_rw_notify_handle, pattern, wlen);
		{
			uint16_t len = read_chrc(props_svc_rw_notify_handle);

			if (len < wlen || memcmp(read_buf, pattern, wlen) != 0) {
				TEST_FAIL("props_svc/rw_notify read-back mismatch");
			}
		}
	}
	{
		uint8_t pattern[PROPS_SVC_RW_INDICATE_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(props_svc_rw_indicate_handle, pattern, wlen);
		{
			uint16_t len = read_chrc(props_svc_rw_indicate_handle);

			if (len < wlen || memcmp(read_buf, pattern, wlen) != 0) {
				TEST_FAIL("props_svc/rw_indicate read-back mismatch");
			}
		}
	}
	{
		uint8_t pattern[PROPS_SVC_WWR_NOTIFY_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		err = bt_gatt_write_without_response(g_conn, props_svc_wwr_notify_handle, pattern,
						     wlen, false);
		if (err < 0) {
			TEST_FAIL("props_svc/wwr_notify write failed (err %d)", err);
		}
		/* Write without response is queued; give it time to land. */
		k_sleep(K_MSEC(100));
	}
	{
		uint8_t pattern[PROPS_SVC_SIGNED_RW_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(props_svc_signed_rw_handle, pattern, wlen);
		{
			uint16_t len = read_chrc(props_svc_signed_rw_handle);

			if (len < wlen || memcmp(read_buf, pattern, wlen) != 0) {
				TEST_FAIL("props_svc/signed_rw read-back mismatch");
			}
		}
	}
	{
		uint8_t pattern[PROPS_SVC_EXT_PROPS_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(props_svc_ext_props_handle, pattern, wlen);
		{
			uint16_t len = read_chrc(props_svc_ext_props_handle);

			if (len < wlen || memcmp(read_buf, pattern, wlen) != 0) {
				TEST_FAIL("props_svc/ext_props read-back mismatch");
			}
		}
	}
	{
		uint8_t pattern[PROPS_SVC_BIG_VALUE_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(props_svc_big_value_handle, pattern, wlen);
		{
			uint16_t len = read_chrc(props_svc_big_value_handle);

			if (len < wlen || memcmp(read_buf, pattern, wlen) != 0) {
				TEST_FAIL("props_svc/big_value read-back mismatch");
			}
		}
	}
	{
		uint8_t pattern[SEC_SVC_ENC_WRITE_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(sec_svc_enc_write_handle, pattern, wlen);
	}
	{
		uint8_t pattern[SEC_SVC_ENC_RW_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(sec_svc_enc_rw_handle, pattern, wlen);
		{
			uint16_t len = read_chrc(sec_svc_enc_rw_handle);

			if (len < wlen || memcmp(read_buf, pattern, wlen) != 0) {
				TEST_FAIL("sec_svc/enc_rw read-back mismatch");
			}
		}
	}
	{
		uint8_t pattern[SEC_SVC_AUTH_RW_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(sec_svc_auth_rw_handle, pattern, wlen);
		{
			uint16_t len = read_chrc(sec_svc_auth_rw_handle);

			if (len < wlen || memcmp(read_buf, pattern, wlen) != 0) {
				TEST_FAIL("sec_svc/auth_rw read-back mismatch");
			}
		}
	}
	{
		uint8_t pattern[SEC_SVC_LESC_RW_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(sec_svc_lesc_rw_handle, pattern, wlen);
		{
			uint16_t len = read_chrc(sec_svc_lesc_rw_handle);

			if (len < wlen || memcmp(read_buf, pattern, wlen) != 0) {
				TEST_FAIL("sec_svc/lesc_rw read-back mismatch");
			}
		}
	}
	{
		uint8_t pattern[DESC_SVC_FULL_META_SIZE];
		/* An ATT write without long-write support is capped at MTU-3. */
		uint16_t wlen = MIN(sizeof(pattern), att_mtu - 3);

		for (size_t i = 0; i < sizeof(pattern); i++) {
			pattern[i] = (uint8_t)(0xa5 ^ i);
		}

		write_chrc(desc_svc_full_meta_handle, pattern, wlen);
		{
			uint16_t len = read_chrc(desc_svc_full_meta_handle);

			if (len < wlen || memcmp(read_buf, pattern, wlen) != 0) {
				TEST_FAIL("desc_svc/full_meta read-back mismatch");
			}
		}
	}

	/* Subscribe to every notification/indication source. */
	props_svc_notify_only_sub.value_handle = props_svc_notify_only_handle;
	err = bt_gatt_subscribe(g_conn, &props_svc_notify_only_sub);
	if (err < 0) {
		TEST_FAIL("props_svc/notify_only subscribe failed (err %d)", err);
	}
	WAIT_FOR_FLAG(props_svc_notify_only_subscribed);
	props_svc_indicate_only_sub.value_handle = props_svc_indicate_only_handle;
	err = bt_gatt_subscribe(g_conn, &props_svc_indicate_only_sub);
	if (err < 0) {
		TEST_FAIL("props_svc/indicate_only subscribe failed (err %d)", err);
	}
	WAIT_FOR_FLAG(props_svc_indicate_only_subscribed);
	props_svc_read_notify_sub.value_handle = props_svc_read_notify_handle;
	err = bt_gatt_subscribe(g_conn, &props_svc_read_notify_sub);
	if (err < 0) {
		TEST_FAIL("props_svc/read_notify subscribe failed (err %d)", err);
	}
	WAIT_FOR_FLAG(props_svc_read_notify_subscribed);
	props_svc_read_indicate_sub.value_handle = props_svc_read_indicate_handle;
	err = bt_gatt_subscribe(g_conn, &props_svc_read_indicate_sub);
	if (err < 0) {
		TEST_FAIL("props_svc/read_indicate subscribe failed (err %d)", err);
	}
	WAIT_FOR_FLAG(props_svc_read_indicate_subscribed);
	props_svc_rw_notify_sub.value_handle = props_svc_rw_notify_handle;
	err = bt_gatt_subscribe(g_conn, &props_svc_rw_notify_sub);
	if (err < 0) {
		TEST_FAIL("props_svc/rw_notify subscribe failed (err %d)", err);
	}
	WAIT_FOR_FLAG(props_svc_rw_notify_subscribed);
	props_svc_rw_indicate_sub.value_handle = props_svc_rw_indicate_handle;
	err = bt_gatt_subscribe(g_conn, &props_svc_rw_indicate_sub);
	if (err < 0) {
		TEST_FAIL("props_svc/rw_indicate subscribe failed (err %d)", err);
	}
	WAIT_FOR_FLAG(props_svc_rw_indicate_subscribed);
	props_svc_wwr_notify_sub.value_handle = props_svc_wwr_notify_handle;
	err = bt_gatt_subscribe(g_conn, &props_svc_wwr_notify_sub);
	if (err < 0) {
		TEST_FAIL("props_svc/wwr_notify subscribe failed (err %d)", err);
	}
	WAIT_FOR_FLAG(props_svc_wwr_notify_subscribed);
	sec_svc_enc_notify_sub.value_handle = sec_svc_enc_notify_handle;
	err = bt_gatt_subscribe(g_conn, &sec_svc_enc_notify_sub);
	if (err < 0) {
		TEST_FAIL("sec_svc/enc_notify subscribe failed (err %d)", err);
	}
	WAIT_FOR_FLAG(sec_svc_enc_notify_subscribed);
	sec_svc_auth_indicate_sub.value_handle = sec_svc_auth_indicate_handle;
	err = bt_gatt_subscribe(g_conn, &sec_svc_auth_indicate_sub);
	if (err < 0) {
		TEST_FAIL("sec_svc/auth_indicate subscribe failed (err %d)", err);
	}
	WAIT_FOR_FLAG(sec_svc_auth_indicate_subscribed);
	desc_svc_described_sub.value_handle = desc_svc_described_handle;
	err = bt_gatt_subscribe(g_conn, &desc_svc_described_sub);
	if (err < 0) {
		TEST_FAIL("desc_svc/described subscribe failed (err %d)", err);
	}
	WAIT_FOR_FLAG(desc_svc_described_subscribed);

	printk("All characteristics verified; signalling peripheral\n");

	/* Tell the peripheral to start pushing values. */
	bk_sync_send();

	/* Wait for the expected pushes. */
	for (int i = 0; i < WAIT_ITERS; i++) {
		if (props_svc_notify_only_received >= NOTIFICATION_COUNT &&
		    props_svc_indicate_only_received >= 1 &&
		    props_svc_read_notify_received >= NOTIFICATION_COUNT &&
		    props_svc_read_indicate_received >= 1 &&
		    props_svc_rw_notify_received >= NOTIFICATION_COUNT &&
		    props_svc_rw_indicate_received >= 1 &&
		    props_svc_wwr_notify_received >= NOTIFICATION_COUNT &&
		    sec_svc_enc_notify_received >= NOTIFICATION_COUNT &&
		    sec_svc_auth_indicate_received >= 1 &&
		    desc_svc_described_received >= NOTIFICATION_COUNT) {
			break;
		}
		k_sleep(K_MSEC(10));
	}
	if (props_svc_notify_only_received < NOTIFICATION_COUNT) {
		TEST_FAIL("props_svc/notify_only: got %u values, expected %u",
			  props_svc_notify_only_received, NOTIFICATION_COUNT);
	}
	if (props_svc_indicate_only_received < 1) {
		TEST_FAIL("props_svc/indicate_only: got %u values, expected %u",
			  props_svc_indicate_only_received, 1);
	}
	if (props_svc_read_notify_received < NOTIFICATION_COUNT) {
		TEST_FAIL("props_svc/read_notify: got %u values, expected %u",
			  props_svc_read_notify_received, NOTIFICATION_COUNT);
	}
	if (props_svc_read_indicate_received < 1) {
		TEST_FAIL("props_svc/read_indicate: got %u values, expected %u",
			  props_svc_read_indicate_received, 1);
	}
	if (props_svc_rw_notify_received < NOTIFICATION_COUNT) {
		TEST_FAIL("props_svc/rw_notify: got %u values, expected %u",
			  props_svc_rw_notify_received, NOTIFICATION_COUNT);
	}
	if (props_svc_rw_indicate_received < 1) {
		TEST_FAIL("props_svc/rw_indicate: got %u values, expected %u",
			  props_svc_rw_indicate_received, 1);
	}
	if (props_svc_wwr_notify_received < NOTIFICATION_COUNT) {
		TEST_FAIL("props_svc/wwr_notify: got %u values, expected %u",
			  props_svc_wwr_notify_received, NOTIFICATION_COUNT);
	}
	if (sec_svc_enc_notify_received < NOTIFICATION_COUNT) {
		TEST_FAIL("sec_svc/enc_notify: got %u values, expected %u",
			  sec_svc_enc_notify_received, NOTIFICATION_COUNT);
	}
	if (sec_svc_auth_indicate_received < 1) {
		TEST_FAIL("sec_svc/auth_indicate: got %u values, expected %u",
			  sec_svc_auth_indicate_received, 1);
	}
	if (desc_svc_described_received < NOTIFICATION_COUNT) {
		TEST_FAIL("desc_svc/described: got %u values, expected %u",
			  desc_svc_described_received, NOTIFICATION_COUNT);
	}

	/* Verification complete; let the peripheral pass. */
	bk_sync_send();

	TEST_PASS("gatt_gen_full central passed");
}

static const struct bst_test_instance test_central_def[] = {
	{
		.test_id = "central",
		.test_main_f = test_central,
	},
	BSTEST_END_MARKER,
};

struct bst_test_list *test_central_install(struct bst_test_list *tests)
{
	return bst_add_tests(tests, test_central_def);
}
