/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_minimal GATT service definition.
 *
 *  Auto-generated by gatt-gen; do not edit.
 */

#ifndef ZEPHYR_GATT_GEN_MINIMAL_SVC_H_
#define ZEPHYR_GATT_GEN_MINIMAL_SVC_H_

#include <stdint.h>
#include <zephyr/bluetooth/gatt.h>

#endif /* ZEPHYR_GATT_GEN_MINIMAL_SVC_H_ */
