/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_minimal GATT service implementation (minimal_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit. Put application logic in
 *  main.c or your own sources and call the public helpers declared in
 *  minimal_svc_service.h.
 */

#include <errno.h>
#include <stdint.h>
#include <string.h>

#include <zephyr/kernel.h>
#include <zephyr/sys/printk.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>

#include "minimal_svc_service.h"

/* ------------------------------------------------------------------------- */
/* Characteristic value storage                                              */
/* ------------------------------------------------------------------------- */

static uint8_t minimal_svc_read_only_value[MINIMAL_SVC_READ_ONLY_SIZE];
static K_MUTEX_DEFINE(minimal_svc_read_only_lock);
static uint8_t minimal_svc_read_write_value[MINIMAL_SVC_READ_WRITE_SIZE];
static K_MUTEX_DEFINE(minimal_svc_read_write_lock);

/* ------------------------------------------------------------------------- */
/* Static descriptor payloads                                                */
/* ------------------------------------------------------------------------- */

/* ------------------------------------------------------------------------- */
/* Thread-safe accessors                                                     */
/* ------------------------------------------------------------------------- */

int minimal_svc_read_only_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(minimal_svc_read_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&minimal_svc_read_only_lock, K_FOREVER);
	memcpy(minimal_svc_read_only_value, data, len);
	k_mutex_unlock(&minimal_svc_read_only_lock);

	return 0;
}

int minimal_svc_read_only_get(uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(minimal_svc_read_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&minimal_svc_read_only_lock, K_FOREVER);
	memcpy(data, minimal_svc_read_only_value, len);
	k_mutex_unlock(&minimal_svc_read_only_lock);

	return 0;
}

int minimal_svc_read_write_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(minimal_svc_read_write_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&minimal_svc_read_write_lock, K_FOREVER);
	memcpy(minimal_svc_read_write_value, data, len);
	k_mutex_unlock(&minimal_svc_read_write_lock);

	return 0;
}

int minimal_svc_read_write_get(uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(minimal_svc_read_write_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&minimal_svc_read_write_lock, K_FOREVER);
	memcpy(data, minimal_svc_read_write_value, len);
	k_mutex_unlock(&minimal_svc_read_write_lock);

	return 0;
}

/* ------------------------------------------------------------------------- */
/* GATT attribute callbacks                                                  */
/* ------------------------------------------------------------------------- */

static ssize_t minimal_svc_read_only_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					  void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	k_mutex_lock(&minimal_svc_read_only_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, minimal_svc_read_only_value,
				sizeof(minimal_svc_read_only_value));
	k_mutex_unlock(&minimal_svc_read_only_lock);

	return ret;
}

static ssize_t minimal_svc_read_write_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					   void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	k_mutex_lock(&minimal_svc_read_write_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, minimal_svc_read_write_value,
				sizeof(minimal_svc_read_write_value));
	k_mutex_unlock(&minimal_svc_read_write_lock);

	return ret;
}

static ssize_t minimal_svc_read_write_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					    const void *buf, uint16_t len, uint16_t offset,
					    uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(minimal_svc_read_write_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&minimal_svc_read_write_lock, K_FOREVER);
	memcpy(minimal_svc_read_write_value + offset, buf, len);
	k_mutex_unlock(&minimal_svc_read_write_lock);

	minimal_svc_read_write_on_write(minimal_svc_read_write_value,
					sizeof(minimal_svc_read_write_value));

	return len;
}

/* ------------------------------------------------------------------------- */
/* Application hooks (weak defaults; override in your own sources)           */
/* ------------------------------------------------------------------------- */

__weak void minimal_svc_read_write_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

/* ------------------------------------------------------------------------- */
/* Push helpers                                                              */
/* ------------------------------------------------------------------------- */

/* ------------------------------------------------------------------------- */
/* Service declaration                                                       */
/* ------------------------------------------------------------------------- */

/* clang-format off */
BT_GATT_SERVICE_DEFINE(minimal_svc,
	BT_GATT_PRIMARY_SERVICE(MINIMAL_SVC_UUID),

	/* read_only: read */
	BT_GATT_CHARACTERISTIC(MINIMAL_SVC_READ_ONLY_UUID,
			       BT_GATT_CHRC_READ,
			       BT_GATT_PERM_READ,
			       minimal_svc_read_only_read,
			       NULL,
			       minimal_svc_read_only_value),

	/* read_write: read, write */
	BT_GATT_CHARACTERISTIC(MINIMAL_SVC_READ_WRITE_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE,
			       minimal_svc_read_write_read,
			       minimal_svc_read_write_write,
			       minimal_svc_read_write_value),
);
/* clang-format on */
