/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_minimal GATT service public API (minimal_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit.
 */

#ifndef BLE_GATT_GENERATOR_MINIMAL_SVC_H_
#define BLE_GATT_GENERATOR_MINIMAL_SVC_H_

#include <stdint.h>

#include <zephyr/bluetooth/uuid.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @defgroup minimal_svc minimal_svc service
 *  @brief Generated helpers for the minimal_svc GATT service.
 *  @{
 */

/* Service and characteristic UUIDs. */
#define MINIMAL_SVC_UUID                                                                           \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef0))
#define MINIMAL_SVC_READ_ONLY_UUID                                                                 \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef1))
#define MINIMAL_SVC_READ_WRITE_UUID                                                                \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef2))

/* Characteristic value sizes in bytes. */
#define MINIMAL_SVC_READ_ONLY_SIZE  1
#define MINIMAL_SVC_READ_WRITE_SIZE 20

/** @brief Set the read_only characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              MINIMAL_SVC_READ_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int minimal_svc_read_only_set(const uint8_t *data, uint16_t len);

/** @brief Get the read_only characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              MINIMAL_SVC_READ_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int minimal_svc_read_only_get(uint8_t *data, uint16_t len);

/** @brief Set the read_write characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              MINIMAL_SVC_READ_WRITE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int minimal_svc_read_write_set(const uint8_t *data, uint16_t len);

/** @brief Get the read_write characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              MINIMAL_SVC_READ_WRITE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int minimal_svc_read_write_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes read_write.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void minimal_svc_read_write_on_write(const uint8_t *data, uint16_t len);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* BLE_GATT_GENERATOR_MINIMAL_SVC_H_ */
