/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_minimal GATT service implementation.
 *
 *  Auto-generated by gatt-gen; do not edit.
 */

#include <stdint.h>
#include <string.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>

#include "minimal_svc_service.h"

/* Internal data */
static uint8_t minimal_svc_read_only_value[1];
static uint8_t minimal_svc_read_write_value[20];

/* Characteristic callbacks */
static ssize_t minimal_svc_read_only_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					  void *buf, uint16_t len, uint16_t offset)
{
	uint8_t *value = (uint8_t *)attr->user_data;

	return bt_gatt_attr_read(conn, attr, buf, len, offset, value, 1);
}
static ssize_t minimal_svc_read_write_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					   void *buf, uint16_t len, uint16_t offset)
{
	uint8_t *value = (uint8_t *)attr->user_data;

	return bt_gatt_attr_read(conn, attr, buf, len, offset, value, 20);
}
static ssize_t minimal_svc_read_write_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					    const void *buf, uint16_t len, uint16_t offset,
					    uint8_t flags)
{
	uint8_t *value = (uint8_t *)attr->user_data;

	if (offset + len > 20) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	memcpy(value + offset, buf, len);

	return len;
}

/* Service declaration */
BT_GATT_SERVICE_DEFINE(
	minimal_svc,
	BT_GATT_PRIMARY_SERVICE(BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678,
								       0x1234, 0x56789abcdef0))),
	BT_GATT_CHARACTERISTIC(BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678,
								      0x1234, 0x56789abcdef1)),
			       BT_GATT_CHRC_READ, BT_GATT_PERM_READ, minimal_svc_read_only_read,
			       NULL, minimal_svc_read_only_value),
	BT_GATT_CHARACTERISTIC(BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678,
								      0x1234, 0x56789abcdef2)),
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, minimal_svc_read_write_read,
			       minimal_svc_read_write_write, minimal_svc_read_write_value));
