#!/usr/bin/env python3
"""Bleak test client for the gatt_gen_secure GATT profile.

Auto-generated by ble-gatt-generator; do not edit.

Usage:
    python test_client.py --name "GATT Gen gatt_gen_secure"
    python test_client.py --address AA:BB:CC:DD:EE:FF --notify-seconds 10
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from typing import Any

from bleak import BleakClient, BleakScanner

DEVICE_NAME = "GATT Gen gatt_gen_secure"

SERVICES: list[dict[str, Any]] = [
    {
        "name": "secure_svc",
        "uuid": "12345678-1234-5678-1234-56789abcdef0",
        "characteristics": [
            {
                "name": "secret",
                "uuid": "12345678-1234-5678-1234-56789abcdef1",
                "size": 16,
                "properties": ["read", "write"],
            },
        ],
    },
]


def _on_notify(sender: Any, data: bytearray) -> None:
    print(f"    <- {sender.uuid}: {data.hex()}")


async def _exercise(client: BleakClient, chrc: dict[str, Any], notify_seconds: float) -> bool:
    ok = True
    props = chrc["properties"]
    uuid = chrc["uuid"]
    print(f"  == {chrc['name']} ({uuid}) {props}")

    if "read" in props:
        value = await client.read_gatt_char(uuid)
        print(f"    read: {value.hex()}")

    if "write" in props or "write_without_response" in props:
        pattern = bytes(i % 256 for i in range(chrc["size"]))
        await client.write_gatt_char(uuid, pattern, response="write" in props)
        print(f"    wrote: {pattern.hex()}")
        if "read" in props:
            value = await client.read_gatt_char(uuid)
            if bytes(value) != pattern:
                print(f"    MISMATCH read back: {value.hex()}")
                ok = False
            else:
                print("    read back matches")

    if "notify" in props or "indicate" in props:
        await client.start_notify(uuid, _on_notify)
        print(f"    waiting {notify_seconds:g}s for notifications/indications ...")
        await asyncio.sleep(notify_seconds)
        await client.stop_notify(uuid)

    return ok


async def _resolve_address(args: argparse.Namespace) -> str | None:
    if args.address:
        return args.address

    print(f"Scanning for '{args.name}' ...")
    device = await BleakScanner.find_device_by_name(args.name, timeout=args.scan_timeout)
    if device is None:
        print(f"Device '{args.name}' not found", file=sys.stderr)
        return None
    return device.address


async def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--name", default=DEVICE_NAME, help="Advertised device name")
    parser.add_argument("--address", help="Bluetooth address (skips scanning)")
    parser.add_argument("--scan-timeout", type=float, default=10.0)
    parser.add_argument("--notify-seconds", type=float, default=5.0,
                        help="How long to listen for notifications per characteristic")
    args = parser.parse_args()

    address = await _resolve_address(args)
    if not address:
        return 1

    print(f"Connecting to {address} ...")
    ok = True
    async with BleakClient(address) as client:
        print("Connected")
        present = {s.uuid.lower() for s in client.services}
        for svc in SERVICES:
            print(f"\n[{svc['name']}] {svc['uuid']}")
            if svc["uuid"] not in present:
                print("  service not found on peer", file=sys.stderr)
                ok = False
                continue
            for chrc in svc["characteristics"]:
                ok &= await _exercise(client, chrc, args.notify_seconds)

    print("\nPASS" if ok else "\nFAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
