/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_full GATT service public API (desc_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit.
 */

#ifndef BLE_GATT_GENERATOR_DESC_SVC_H_
#define BLE_GATT_GENERATOR_DESC_SVC_H_

#include <stdint.h>

#include <zephyr/bluetooth/uuid.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @defgroup desc_svc desc_svc service
 *  @brief Generated helpers for the desc_svc GATT service.
 *  @{
 */

/* Service and characteristic UUIDs. */
#define DESC_SVC_UUID                                                                              \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde40))
#define DESC_SVC_DESCRIBED_UUID                                                                    \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde41))
#define DESC_SVC_FULL_META_UUID                                                                    \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde42))
#define DESC_SVC_PLAIN_UUID                                                                        \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde43))

/* Characteristic value sizes in bytes. */
#define DESC_SVC_DESCRIBED_SIZE 4
#define DESC_SVC_FULL_META_SIZE 16
#define DESC_SVC_PLAIN_SIZE     4

/** @brief Set the described characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              DESC_SVC_DESCRIBED_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int desc_svc_described_set(const uint8_t *data, uint16_t len);

/** @brief Get the described characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              DESC_SVC_DESCRIBED_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int desc_svc_described_get(uint8_t *data, uint16_t len);

/** @brief Update and notify the described characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_notify_uuid()).
 */
int desc_svc_described_notify(const uint8_t *data, uint16_t len);

/** @brief Set the full_meta characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              DESC_SVC_FULL_META_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int desc_svc_full_meta_set(const uint8_t *data, uint16_t len);

/** @brief Get the full_meta characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              DESC_SVC_FULL_META_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int desc_svc_full_meta_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes full_meta.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void desc_svc_full_meta_on_write(const uint8_t *data, uint16_t len);

/** @brief Set the plain characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              DESC_SVC_PLAIN_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int desc_svc_plain_set(const uint8_t *data, uint16_t len);

/** @brief Get the plain characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              DESC_SVC_PLAIN_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int desc_svc_plain_get(uint8_t *data, uint16_t len);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* BLE_GATT_GENERATOR_DESC_SVC_H_ */
