/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_full GATT service implementation (desc_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit. Put application logic in
 *  main.c or your own sources and call the public helpers declared in
 *  desc_svc_service.h.
 */

#include <errno.h>
#include <stdint.h>
#include <string.h>

#include <zephyr/kernel.h>
#include <zephyr/sys/printk.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>

#include "desc_svc_service.h"

/* ------------------------------------------------------------------------- */
/* Characteristic value storage                                              */
/* ------------------------------------------------------------------------- */

static uint8_t desc_svc_described_value[DESC_SVC_DESCRIBED_SIZE];
static K_MUTEX_DEFINE(desc_svc_described_lock);
static uint8_t desc_svc_full_meta_value[DESC_SVC_FULL_META_SIZE];
static K_MUTEX_DEFINE(desc_svc_full_meta_lock);
static uint8_t desc_svc_plain_value[DESC_SVC_PLAIN_SIZE];
static K_MUTEX_DEFINE(desc_svc_plain_lock);

/* ------------------------------------------------------------------------- */
/* Static descriptor payloads                                                */
/* ------------------------------------------------------------------------- */

static const struct bt_gatt_cpf desc_svc_described_cpf = {
	.format = 4,
	.exponent = 0,
	.unit = 10157,
	.name_space = 1,
	.description = 0,
};
static const struct bt_gatt_cpf desc_svc_full_meta_cpf = {
	.format = 8,
	.exponent = 0,
	.unit = 0,
	.name_space = 1,
	.description = 0,
};
static const struct bt_gatt_cep desc_svc_full_meta_cep = {
	.properties = BT_GATT_CEP_RELIABLE_WRITE,
};

/* ------------------------------------------------------------------------- */
/* Thread-safe accessors                                                     */
/* ------------------------------------------------------------------------- */

int desc_svc_described_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(desc_svc_described_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&desc_svc_described_lock, K_FOREVER);
	memcpy(desc_svc_described_value, data, len);
	k_mutex_unlock(&desc_svc_described_lock);

	return 0;
}

int desc_svc_described_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(desc_svc_described_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&desc_svc_described_lock, K_FOREVER);
	memcpy(data, desc_svc_described_value, MIN(len, sizeof(desc_svc_described_value)));
	k_mutex_unlock(&desc_svc_described_lock);

	return 0;
}

int desc_svc_full_meta_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(desc_svc_full_meta_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&desc_svc_full_meta_lock, K_FOREVER);
	memcpy(desc_svc_full_meta_value, data, len);
	k_mutex_unlock(&desc_svc_full_meta_lock);

	return 0;
}

int desc_svc_full_meta_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(desc_svc_full_meta_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&desc_svc_full_meta_lock, K_FOREVER);
	memcpy(data, desc_svc_full_meta_value, MIN(len, sizeof(desc_svc_full_meta_value)));
	k_mutex_unlock(&desc_svc_full_meta_lock);

	return 0;
}

int desc_svc_plain_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(desc_svc_plain_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&desc_svc_plain_lock, K_FOREVER);
	memcpy(desc_svc_plain_value, data, len);
	k_mutex_unlock(&desc_svc_plain_lock);

	return 0;
}

int desc_svc_plain_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(desc_svc_plain_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&desc_svc_plain_lock, K_FOREVER);
	memcpy(data, desc_svc_plain_value, MIN(len, sizeof(desc_svc_plain_value)));
	k_mutex_unlock(&desc_svc_plain_lock);

	return 0;
}

/* ------------------------------------------------------------------------- */
/* GATT attribute callbacks                                                  */
/* ------------------------------------------------------------------------- */

static ssize_t desc_svc_described_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				       void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	desc_svc_described_on_read();

	k_mutex_lock(&desc_svc_described_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, desc_svc_described_value,
				sizeof(desc_svc_described_value));
	k_mutex_unlock(&desc_svc_described_lock);

	return ret;
}

static void desc_svc_described_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_NOTIFY;

	ARG_UNUSED(attr);

	printk("described notifications %s\n", enabled ? "enabled" : "disabled");

	desc_svc_described_on_ccc(enabled);
}

static ssize_t desc_svc_full_meta_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				       void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	desc_svc_full_meta_on_read();

	k_mutex_lock(&desc_svc_full_meta_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, desc_svc_full_meta_value,
				sizeof(desc_svc_full_meta_value));
	k_mutex_unlock(&desc_svc_full_meta_lock);

	return ret;
}

static ssize_t desc_svc_full_meta_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					const void *buf, uint16_t len, uint16_t offset,
					uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(desc_svc_full_meta_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&desc_svc_full_meta_lock, K_FOREVER);
	memcpy(desc_svc_full_meta_value + offset, buf, len);
	k_mutex_unlock(&desc_svc_full_meta_lock);

	desc_svc_full_meta_on_write(desc_svc_full_meta_value, sizeof(desc_svc_full_meta_value));

	return len;
}

static ssize_t desc_svc_plain_read(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf,
				   uint16_t len, uint16_t offset)
{
	ssize_t ret;

	desc_svc_plain_on_read();

	k_mutex_lock(&desc_svc_plain_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, desc_svc_plain_value,
				sizeof(desc_svc_plain_value));
	k_mutex_unlock(&desc_svc_plain_lock);

	return ret;
}

/* ------------------------------------------------------------------------- */
/* Application hooks (weak defaults; override in your own sources)           */
/* ------------------------------------------------------------------------- */

__weak void desc_svc_described_on_read(void)
{
}
__weak void desc_svc_described_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

__weak void desc_svc_full_meta_on_read(void)
{
}
__weak void desc_svc_full_meta_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

__weak void desc_svc_plain_on_read(void)
{
}

/* ------------------------------------------------------------------------- */
/* Push helpers                                                              */
/* ------------------------------------------------------------------------- */

int desc_svc_described_notify(const uint8_t *data, uint16_t len)
{
	int err;

	err = desc_svc_described_set(data, len);
	if (err) {
		return err;
	}

	return bt_gatt_notify_uuid(NULL, DESC_SVC_DESCRIBED_UUID, NULL, desc_svc_described_value,
				   len);
}

/* ------------------------------------------------------------------------- */
/* Service declaration                                                       */
/* ------------------------------------------------------------------------- */

/* clang-format off */
BT_GATT_SERVICE_DEFINE(desc_svc,
	BT_GATT_PRIMARY_SERVICE(DESC_SVC_UUID),

	/* described: read, notify */
	BT_GATT_CHARACTERISTIC(DESC_SVC_DESCRIBED_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_NOTIFY,
			       BT_GATT_PERM_READ,
			       desc_svc_described_read,
			       NULL,
			       desc_svc_described_value),
	BT_GATT_CUD("Fully described value", BT_GATT_PERM_READ),
	BT_GATT_CPF(&desc_svc_described_cpf),
	BT_GATT_CCC(desc_svc_described_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* full_meta: read, write, extended_properties */
	BT_GATT_CHARACTERISTIC(DESC_SVC_FULL_META_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE | BT_GATT_CHRC_EXT_PROP,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE | BT_GATT_PERM_PREPARE_WRITE,
			       desc_svc_full_meta_read,
			       desc_svc_full_meta_write,
			       desc_svc_full_meta_value),
	BT_GATT_CUD("All descriptors present", BT_GATT_PERM_READ),
	BT_GATT_CPF(&desc_svc_full_meta_cpf),
	BT_GATT_CEP(&desc_svc_full_meta_cep),

	/* plain: read */
	BT_GATT_CHARACTERISTIC(DESC_SVC_PLAIN_UUID,
			       BT_GATT_CHRC_READ,
			       BT_GATT_PERM_READ,
			       desc_svc_plain_read,
			       NULL,
			       desc_svc_plain_value),
);
/* clang-format on */
