/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_full GATT service public API (props_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit.
 */

#ifndef BLE_GATT_GENERATOR_PROPS_SVC_H_
#define BLE_GATT_GENERATOR_PROPS_SVC_H_

#include <stdbool.h>
#include <stdint.h>

#include <zephyr/bluetooth/uuid.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @defgroup props_svc props_svc service
 *  @brief Generated helpers for the props_svc GATT service.
 *  @{
 */

/* Service and characteristic UUIDs. */
#define PROPS_SVC_UUID                                                                             \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef0))
#define PROPS_SVC_READ_ONLY_UUID                                                                   \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde01))
#define PROPS_SVC_WRITE_ONLY_UUID                                                                  \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde02))
#define PROPS_SVC_WWR_ONLY_UUID                                                                    \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde03))
#define PROPS_SVC_READ_WRITE_UUID                                                                  \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde04))
#define PROPS_SVC_NOTIFY_ONLY_UUID                                                                 \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde05))
#define PROPS_SVC_INDICATE_ONLY_UUID                                                               \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde06))
#define PROPS_SVC_READ_NOTIFY_UUID                                                                 \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde07))
#define PROPS_SVC_READ_INDICATE_UUID                                                               \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde08))
#define PROPS_SVC_RW_NOTIFY_UUID                                                                   \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde09))
#define PROPS_SVC_RW_INDICATE_UUID                                                                 \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde0a))
#define PROPS_SVC_WWR_NOTIFY_UUID                                                                  \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde0b))
#define PROPS_SVC_BROADCAST_CHRC_UUID                                                              \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde0c))
#define PROPS_SVC_SIGNED_RW_UUID                                                                   \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde0d))
#define PROPS_SVC_EXT_PROPS_UUID                                                                   \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde0e))
#define PROPS_SVC_BIG_VALUE_UUID                                                                   \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde0f))

/* Characteristic value sizes in bytes. */
#define PROPS_SVC_READ_ONLY_SIZE      8
#define PROPS_SVC_WRITE_ONLY_SIZE     8
#define PROPS_SVC_WWR_ONLY_SIZE       8
#define PROPS_SVC_READ_WRITE_SIZE     8
#define PROPS_SVC_NOTIFY_ONLY_SIZE    4
#define PROPS_SVC_INDICATE_ONLY_SIZE  4
#define PROPS_SVC_READ_NOTIFY_SIZE    8
#define PROPS_SVC_READ_INDICATE_SIZE  8
#define PROPS_SVC_RW_NOTIFY_SIZE      8
#define PROPS_SVC_RW_INDICATE_SIZE    8
#define PROPS_SVC_WWR_NOTIFY_SIZE     8
#define PROPS_SVC_BROADCAST_CHRC_SIZE 4
#define PROPS_SVC_SIGNED_RW_SIZE      8
#define PROPS_SVC_EXT_PROPS_SIZE      16
#define PROPS_SVC_BIG_VALUE_SIZE      64

/** @brief Set the read_only characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_READ_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_read_only_set(const uint8_t *data, uint16_t len);

/** @brief Get the read_only characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_READ_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_read_only_get(uint8_t *data, uint16_t len);

/** @brief Application hook called before a peer reads read_only.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to refresh the value or gate the read; it runs from the Bluetooth
 *  RX context, so keep it short.
 */
void props_svc_read_only_on_read(void);

/** @brief Set the write_only characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_WRITE_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_write_only_set(const uint8_t *data, uint16_t len);

/** @brief Get the write_only characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_WRITE_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_write_only_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes write_only.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void props_svc_write_only_on_write(const uint8_t *data, uint16_t len);

/** @brief Set the wwr_only characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_WWR_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_wwr_only_set(const uint8_t *data, uint16_t len);

/** @brief Get the wwr_only characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_WWR_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_wwr_only_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes wwr_only.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void props_svc_wwr_only_on_write(const uint8_t *data, uint16_t len);

/** @brief Set the read_write characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_READ_WRITE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_read_write_set(const uint8_t *data, uint16_t len);

/** @brief Get the read_write characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_READ_WRITE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_read_write_get(uint8_t *data, uint16_t len);

/** @brief Application hook called before a peer reads read_write.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to refresh the value or gate the read; it runs from the Bluetooth
 *  RX context, so keep it short.
 */
void props_svc_read_write_on_read(void);

/** @brief Application hook called after a peer writes read_write.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void props_svc_read_write_on_write(const uint8_t *data, uint16_t len);

/** @brief Set the notify_only characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_NOTIFY_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_notify_only_set(const uint8_t *data, uint16_t len);

/** @brief Get the notify_only characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_NOTIFY_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_notify_only_get(uint8_t *data, uint16_t len);

/** @brief Update and notify the notify_only characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_notify_uuid()).
 */
int props_svc_notify_only_notify(const uint8_t *data, uint16_t len);

/** @brief Application hook called when notify_only CCC state changes.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to react to a peer enabling/disabling
 *  notifications.
 *
 *  @param enabled True when notifications were enabled.
 */
void props_svc_notify_only_on_ccc(bool enabled);

/** @brief Set the indicate_only characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_INDICATE_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_indicate_only_set(const uint8_t *data, uint16_t len);

/** @brief Get the indicate_only characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_INDICATE_ONLY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_indicate_only_get(uint8_t *data, uint16_t len);

/** @brief Update and indicate the indicate_only characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_indicate()).
 */
int props_svc_indicate_only_indicate(const uint8_t *data, uint16_t len);

/** @brief Application hook called when indicate_only CCC state changes.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to react to a peer enabling/disabling
 *  indications.
 *
 *  @param enabled True when indications were enabled.
 */
void props_svc_indicate_only_on_ccc(bool enabled);

/** @brief Set the read_notify characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_READ_NOTIFY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_read_notify_set(const uint8_t *data, uint16_t len);

/** @brief Get the read_notify characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_READ_NOTIFY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_read_notify_get(uint8_t *data, uint16_t len);

/** @brief Application hook called before a peer reads read_notify.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to refresh the value or gate the read; it runs from the Bluetooth
 *  RX context, so keep it short.
 */
void props_svc_read_notify_on_read(void);

/** @brief Update and notify the read_notify characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_notify_uuid()).
 */
int props_svc_read_notify_notify(const uint8_t *data, uint16_t len);

/** @brief Application hook called when read_notify CCC state changes.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to react to a peer enabling/disabling
 *  notifications.
 *
 *  @param enabled True when notifications were enabled.
 */
void props_svc_read_notify_on_ccc(bool enabled);

/** @brief Set the read_indicate characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_READ_INDICATE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_read_indicate_set(const uint8_t *data, uint16_t len);

/** @brief Get the read_indicate characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_READ_INDICATE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_read_indicate_get(uint8_t *data, uint16_t len);

/** @brief Application hook called before a peer reads read_indicate.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to refresh the value or gate the read; it runs from the Bluetooth
 *  RX context, so keep it short.
 */
void props_svc_read_indicate_on_read(void);

/** @brief Update and indicate the read_indicate characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_indicate()).
 */
int props_svc_read_indicate_indicate(const uint8_t *data, uint16_t len);

/** @brief Application hook called when read_indicate CCC state changes.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to react to a peer enabling/disabling
 *  indications.
 *
 *  @param enabled True when indications were enabled.
 */
void props_svc_read_indicate_on_ccc(bool enabled);

/** @brief Set the rw_notify characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_RW_NOTIFY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_rw_notify_set(const uint8_t *data, uint16_t len);

/** @brief Get the rw_notify characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_RW_NOTIFY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_rw_notify_get(uint8_t *data, uint16_t len);

/** @brief Application hook called before a peer reads rw_notify.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to refresh the value or gate the read; it runs from the Bluetooth
 *  RX context, so keep it short.
 */
void props_svc_rw_notify_on_read(void);

/** @brief Application hook called after a peer writes rw_notify.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void props_svc_rw_notify_on_write(const uint8_t *data, uint16_t len);

/** @brief Update and notify the rw_notify characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_notify_uuid()).
 */
int props_svc_rw_notify_notify(const uint8_t *data, uint16_t len);

/** @brief Application hook called when rw_notify CCC state changes.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to react to a peer enabling/disabling
 *  notifications.
 *
 *  @param enabled True when notifications were enabled.
 */
void props_svc_rw_notify_on_ccc(bool enabled);

/** @brief Set the rw_indicate characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_RW_INDICATE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_rw_indicate_set(const uint8_t *data, uint16_t len);

/** @brief Get the rw_indicate characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_RW_INDICATE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_rw_indicate_get(uint8_t *data, uint16_t len);

/** @brief Application hook called before a peer reads rw_indicate.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to refresh the value or gate the read; it runs from the Bluetooth
 *  RX context, so keep it short.
 */
void props_svc_rw_indicate_on_read(void);

/** @brief Application hook called after a peer writes rw_indicate.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void props_svc_rw_indicate_on_write(const uint8_t *data, uint16_t len);

/** @brief Update and indicate the rw_indicate characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_indicate()).
 */
int props_svc_rw_indicate_indicate(const uint8_t *data, uint16_t len);

/** @brief Application hook called when rw_indicate CCC state changes.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to react to a peer enabling/disabling
 *  indications.
 *
 *  @param enabled True when indications were enabled.
 */
void props_svc_rw_indicate_on_ccc(bool enabled);

/** @brief Set the wwr_notify characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_WWR_NOTIFY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_wwr_notify_set(const uint8_t *data, uint16_t len);

/** @brief Get the wwr_notify characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_WWR_NOTIFY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_wwr_notify_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes wwr_notify.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void props_svc_wwr_notify_on_write(const uint8_t *data, uint16_t len);

/** @brief Update and notify the wwr_notify characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_notify_uuid()).
 */
int props_svc_wwr_notify_notify(const uint8_t *data, uint16_t len);

/** @brief Application hook called when wwr_notify CCC state changes.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to react to a peer enabling/disabling
 *  notifications.
 *
 *  @param enabled True when notifications were enabled.
 */
void props_svc_wwr_notify_on_ccc(bool enabled);

/** @brief Set the broadcast_chrc characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_BROADCAST_CHRC_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_broadcast_chrc_set(const uint8_t *data, uint16_t len);

/** @brief Get the broadcast_chrc characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_BROADCAST_CHRC_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_broadcast_chrc_get(uint8_t *data, uint16_t len);

/** @brief Application hook called before a peer reads broadcast_chrc.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to refresh the value or gate the read; it runs from the Bluetooth
 *  RX context, so keep it short.
 */
void props_svc_broadcast_chrc_on_read(void);

/** @brief Set the signed_rw characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_SIGNED_RW_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_signed_rw_set(const uint8_t *data, uint16_t len);

/** @brief Get the signed_rw characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_SIGNED_RW_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_signed_rw_get(uint8_t *data, uint16_t len);

/** @brief Application hook called before a peer reads signed_rw.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to refresh the value or gate the read; it runs from the Bluetooth
 *  RX context, so keep it short.
 */
void props_svc_signed_rw_on_read(void);

/** @brief Application hook called after a peer writes signed_rw.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void props_svc_signed_rw_on_write(const uint8_t *data, uint16_t len);

/** @brief Set the ext_props characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_EXT_PROPS_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_ext_props_set(const uint8_t *data, uint16_t len);

/** @brief Get the ext_props characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_EXT_PROPS_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_ext_props_get(uint8_t *data, uint16_t len);

/** @brief Application hook called before a peer reads ext_props.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to refresh the value or gate the read; it runs from the Bluetooth
 *  RX context, so keep it short.
 */
void props_svc_ext_props_on_read(void);

/** @brief Application hook called after a peer writes ext_props.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void props_svc_ext_props_on_write(const uint8_t *data, uint16_t len);

/** @brief Set the big_value characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_BIG_VALUE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_big_value_set(const uint8_t *data, uint16_t len);

/** @brief Get the big_value characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              PROPS_SVC_BIG_VALUE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int props_svc_big_value_get(uint8_t *data, uint16_t len);

/** @brief Application hook called before a peer reads big_value.
 *
 *  Defined as a weak no-op in the generated source. Define it in your own
 *  code to refresh the value or gate the read; it runs from the Bluetooth
 *  RX context, so keep it short.
 */
void props_svc_big_value_on_read(void);

/** @brief Application hook called after a peer writes big_value.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void props_svc_big_value_on_write(const uint8_t *data, uint16_t len);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* BLE_GATT_GENERATOR_PROPS_SVC_H_ */
