/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_full GATT service implementation (props_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit. Put application logic in
 *  main.c or your own sources and call the public helpers declared in
 *  props_svc_service.h.
 */

#include <errno.h>
#include <stdint.h>
#include <string.h>

#include <zephyr/kernel.h>
#include <zephyr/sys/printk.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>

#include "props_svc_service.h"

/* ------------------------------------------------------------------------- */
/* Characteristic value storage                                              */
/* ------------------------------------------------------------------------- */

static uint8_t props_svc_read_only_value[PROPS_SVC_READ_ONLY_SIZE];
static K_MUTEX_DEFINE(props_svc_read_only_lock);
static uint8_t props_svc_write_only_value[PROPS_SVC_WRITE_ONLY_SIZE];
static K_MUTEX_DEFINE(props_svc_write_only_lock);
static uint8_t props_svc_wwr_only_value[PROPS_SVC_WWR_ONLY_SIZE];
static K_MUTEX_DEFINE(props_svc_wwr_only_lock);
static uint8_t props_svc_read_write_value[PROPS_SVC_READ_WRITE_SIZE];
static K_MUTEX_DEFINE(props_svc_read_write_lock);
static uint8_t props_svc_notify_only_value[PROPS_SVC_NOTIFY_ONLY_SIZE];
static K_MUTEX_DEFINE(props_svc_notify_only_lock);
static uint8_t props_svc_indicate_only_value[PROPS_SVC_INDICATE_ONLY_SIZE];
static K_MUTEX_DEFINE(props_svc_indicate_only_lock);
static uint8_t props_svc_read_notify_value[PROPS_SVC_READ_NOTIFY_SIZE];
static K_MUTEX_DEFINE(props_svc_read_notify_lock);
static uint8_t props_svc_read_indicate_value[PROPS_SVC_READ_INDICATE_SIZE];
static K_MUTEX_DEFINE(props_svc_read_indicate_lock);
static uint8_t props_svc_rw_notify_value[PROPS_SVC_RW_NOTIFY_SIZE];
static K_MUTEX_DEFINE(props_svc_rw_notify_lock);
static uint8_t props_svc_rw_indicate_value[PROPS_SVC_RW_INDICATE_SIZE];
static K_MUTEX_DEFINE(props_svc_rw_indicate_lock);
static uint8_t props_svc_wwr_notify_value[PROPS_SVC_WWR_NOTIFY_SIZE];
static K_MUTEX_DEFINE(props_svc_wwr_notify_lock);
static uint8_t props_svc_broadcast_chrc_value[PROPS_SVC_BROADCAST_CHRC_SIZE];
static K_MUTEX_DEFINE(props_svc_broadcast_chrc_lock);
static uint8_t props_svc_signed_rw_value[PROPS_SVC_SIGNED_RW_SIZE];
static K_MUTEX_DEFINE(props_svc_signed_rw_lock);
static uint8_t props_svc_ext_props_value[PROPS_SVC_EXT_PROPS_SIZE];
static K_MUTEX_DEFINE(props_svc_ext_props_lock);
static uint8_t props_svc_big_value_value[PROPS_SVC_BIG_VALUE_SIZE];
static K_MUTEX_DEFINE(props_svc_big_value_lock);

/* ------------------------------------------------------------------------- */
/* Static descriptor payloads                                                */
/* ------------------------------------------------------------------------- */

static const struct bt_gatt_cep props_svc_ext_props_cep = {
	.properties = BT_GATT_CEP_RELIABLE_WRITE,
};

/* ------------------------------------------------------------------------- */
/* Thread-safe accessors                                                     */
/* ------------------------------------------------------------------------- */

int props_svc_read_only_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_read_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_read_only_lock, K_FOREVER);
	memcpy(props_svc_read_only_value, data, len);
	k_mutex_unlock(&props_svc_read_only_lock);

	return 0;
}

int props_svc_read_only_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_read_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_read_only_lock, K_FOREVER);
	memcpy(data, props_svc_read_only_value, MIN(len, sizeof(props_svc_read_only_value)));
	k_mutex_unlock(&props_svc_read_only_lock);

	return 0;
}

int props_svc_write_only_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_write_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_write_only_lock, K_FOREVER);
	memcpy(props_svc_write_only_value, data, len);
	k_mutex_unlock(&props_svc_write_only_lock);

	return 0;
}

int props_svc_write_only_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_write_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_write_only_lock, K_FOREVER);
	memcpy(data, props_svc_write_only_value, MIN(len, sizeof(props_svc_write_only_value)));
	k_mutex_unlock(&props_svc_write_only_lock);

	return 0;
}

int props_svc_wwr_only_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_wwr_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_wwr_only_lock, K_FOREVER);
	memcpy(props_svc_wwr_only_value, data, len);
	k_mutex_unlock(&props_svc_wwr_only_lock);

	return 0;
}

int props_svc_wwr_only_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_wwr_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_wwr_only_lock, K_FOREVER);
	memcpy(data, props_svc_wwr_only_value, MIN(len, sizeof(props_svc_wwr_only_value)));
	k_mutex_unlock(&props_svc_wwr_only_lock);

	return 0;
}

int props_svc_read_write_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_read_write_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_read_write_lock, K_FOREVER);
	memcpy(props_svc_read_write_value, data, len);
	k_mutex_unlock(&props_svc_read_write_lock);

	return 0;
}

int props_svc_read_write_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_read_write_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_read_write_lock, K_FOREVER);
	memcpy(data, props_svc_read_write_value, MIN(len, sizeof(props_svc_read_write_value)));
	k_mutex_unlock(&props_svc_read_write_lock);

	return 0;
}

int props_svc_notify_only_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_notify_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_notify_only_lock, K_FOREVER);
	memcpy(props_svc_notify_only_value, data, len);
	k_mutex_unlock(&props_svc_notify_only_lock);

	return 0;
}

int props_svc_notify_only_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_notify_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_notify_only_lock, K_FOREVER);
	memcpy(data, props_svc_notify_only_value, MIN(len, sizeof(props_svc_notify_only_value)));
	k_mutex_unlock(&props_svc_notify_only_lock);

	return 0;
}

int props_svc_indicate_only_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_indicate_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_indicate_only_lock, K_FOREVER);
	memcpy(props_svc_indicate_only_value, data, len);
	k_mutex_unlock(&props_svc_indicate_only_lock);

	return 0;
}

int props_svc_indicate_only_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_indicate_only_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_indicate_only_lock, K_FOREVER);
	memcpy(data, props_svc_indicate_only_value,
	       MIN(len, sizeof(props_svc_indicate_only_value)));
	k_mutex_unlock(&props_svc_indicate_only_lock);

	return 0;
}

int props_svc_read_notify_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_read_notify_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_read_notify_lock, K_FOREVER);
	memcpy(props_svc_read_notify_value, data, len);
	k_mutex_unlock(&props_svc_read_notify_lock);

	return 0;
}

int props_svc_read_notify_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_read_notify_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_read_notify_lock, K_FOREVER);
	memcpy(data, props_svc_read_notify_value, MIN(len, sizeof(props_svc_read_notify_value)));
	k_mutex_unlock(&props_svc_read_notify_lock);

	return 0;
}

int props_svc_read_indicate_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_read_indicate_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_read_indicate_lock, K_FOREVER);
	memcpy(props_svc_read_indicate_value, data, len);
	k_mutex_unlock(&props_svc_read_indicate_lock);

	return 0;
}

int props_svc_read_indicate_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_read_indicate_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_read_indicate_lock, K_FOREVER);
	memcpy(data, props_svc_read_indicate_value,
	       MIN(len, sizeof(props_svc_read_indicate_value)));
	k_mutex_unlock(&props_svc_read_indicate_lock);

	return 0;
}

int props_svc_rw_notify_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_rw_notify_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_rw_notify_lock, K_FOREVER);
	memcpy(props_svc_rw_notify_value, data, len);
	k_mutex_unlock(&props_svc_rw_notify_lock);

	return 0;
}

int props_svc_rw_notify_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_rw_notify_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_rw_notify_lock, K_FOREVER);
	memcpy(data, props_svc_rw_notify_value, MIN(len, sizeof(props_svc_rw_notify_value)));
	k_mutex_unlock(&props_svc_rw_notify_lock);

	return 0;
}

int props_svc_rw_indicate_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_rw_indicate_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_rw_indicate_lock, K_FOREVER);
	memcpy(props_svc_rw_indicate_value, data, len);
	k_mutex_unlock(&props_svc_rw_indicate_lock);

	return 0;
}

int props_svc_rw_indicate_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_rw_indicate_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_rw_indicate_lock, K_FOREVER);
	memcpy(data, props_svc_rw_indicate_value, MIN(len, sizeof(props_svc_rw_indicate_value)));
	k_mutex_unlock(&props_svc_rw_indicate_lock);

	return 0;
}

int props_svc_wwr_notify_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_wwr_notify_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_wwr_notify_lock, K_FOREVER);
	memcpy(props_svc_wwr_notify_value, data, len);
	k_mutex_unlock(&props_svc_wwr_notify_lock);

	return 0;
}

int props_svc_wwr_notify_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_wwr_notify_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_wwr_notify_lock, K_FOREVER);
	memcpy(data, props_svc_wwr_notify_value, MIN(len, sizeof(props_svc_wwr_notify_value)));
	k_mutex_unlock(&props_svc_wwr_notify_lock);

	return 0;
}

int props_svc_broadcast_chrc_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_broadcast_chrc_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_broadcast_chrc_lock, K_FOREVER);
	memcpy(props_svc_broadcast_chrc_value, data, len);
	k_mutex_unlock(&props_svc_broadcast_chrc_lock);

	return 0;
}

int props_svc_broadcast_chrc_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_broadcast_chrc_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_broadcast_chrc_lock, K_FOREVER);
	memcpy(data, props_svc_broadcast_chrc_value,
	       MIN(len, sizeof(props_svc_broadcast_chrc_value)));
	k_mutex_unlock(&props_svc_broadcast_chrc_lock);

	return 0;
}

int props_svc_signed_rw_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_signed_rw_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_signed_rw_lock, K_FOREVER);
	memcpy(props_svc_signed_rw_value, data, len);
	k_mutex_unlock(&props_svc_signed_rw_lock);

	return 0;
}

int props_svc_signed_rw_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_signed_rw_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_signed_rw_lock, K_FOREVER);
	memcpy(data, props_svc_signed_rw_value, MIN(len, sizeof(props_svc_signed_rw_value)));
	k_mutex_unlock(&props_svc_signed_rw_lock);

	return 0;
}

int props_svc_ext_props_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_ext_props_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_ext_props_lock, K_FOREVER);
	memcpy(props_svc_ext_props_value, data, len);
	k_mutex_unlock(&props_svc_ext_props_lock);

	return 0;
}

int props_svc_ext_props_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_ext_props_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_ext_props_lock, K_FOREVER);
	memcpy(data, props_svc_ext_props_value, MIN(len, sizeof(props_svc_ext_props_value)));
	k_mutex_unlock(&props_svc_ext_props_lock);

	return 0;
}

int props_svc_big_value_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(props_svc_big_value_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_big_value_lock, K_FOREVER);
	memcpy(props_svc_big_value_value, data, len);
	k_mutex_unlock(&props_svc_big_value_lock);

	return 0;
}

int props_svc_big_value_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(props_svc_big_value_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&props_svc_big_value_lock, K_FOREVER);
	memcpy(data, props_svc_big_value_value, MIN(len, sizeof(props_svc_big_value_value)));
	k_mutex_unlock(&props_svc_big_value_lock);

	return 0;
}

/* ------------------------------------------------------------------------- */
/* GATT attribute callbacks                                                  */
/* ------------------------------------------------------------------------- */

static ssize_t props_svc_read_only_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	props_svc_read_only_on_read();

	k_mutex_lock(&props_svc_read_only_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, props_svc_read_only_value,
				sizeof(props_svc_read_only_value));
	k_mutex_unlock(&props_svc_read_only_lock);

	return ret;
}

static ssize_t props_svc_write_only_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					  const void *buf, uint16_t len, uint16_t offset,
					  uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(props_svc_write_only_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&props_svc_write_only_lock, K_FOREVER);
	memcpy(props_svc_write_only_value + offset, buf, len);
	k_mutex_unlock(&props_svc_write_only_lock);

	props_svc_write_only_on_write(props_svc_write_only_value,
				      sizeof(props_svc_write_only_value));

	return len;
}

static ssize_t props_svc_wwr_only_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					const void *buf, uint16_t len, uint16_t offset,
					uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(props_svc_wwr_only_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&props_svc_wwr_only_lock, K_FOREVER);
	memcpy(props_svc_wwr_only_value + offset, buf, len);
	k_mutex_unlock(&props_svc_wwr_only_lock);

	props_svc_wwr_only_on_write(props_svc_wwr_only_value, sizeof(props_svc_wwr_only_value));

	return len;
}

static ssize_t props_svc_read_write_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					 void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	props_svc_read_write_on_read();

	k_mutex_lock(&props_svc_read_write_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, props_svc_read_write_value,
				sizeof(props_svc_read_write_value));
	k_mutex_unlock(&props_svc_read_write_lock);

	return ret;
}

static ssize_t props_svc_read_write_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					  const void *buf, uint16_t len, uint16_t offset,
					  uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(props_svc_read_write_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&props_svc_read_write_lock, K_FOREVER);
	memcpy(props_svc_read_write_value + offset, buf, len);
	k_mutex_unlock(&props_svc_read_write_lock);

	props_svc_read_write_on_write(props_svc_read_write_value,
				      sizeof(props_svc_read_write_value));

	return len;
}

static void props_svc_notify_only_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_NOTIFY;

	ARG_UNUSED(attr);

	printk("notify_only notifications %s\n", enabled ? "enabled" : "disabled");

	props_svc_notify_only_on_ccc(enabled);
}

static void props_svc_indicate_only_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_INDICATE;

	ARG_UNUSED(attr);

	printk("indicate_only indications %s\n", enabled ? "enabled" : "disabled");

	props_svc_indicate_only_on_ccc(enabled);
}

static ssize_t props_svc_read_notify_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					  void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	props_svc_read_notify_on_read();

	k_mutex_lock(&props_svc_read_notify_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, props_svc_read_notify_value,
				sizeof(props_svc_read_notify_value));
	k_mutex_unlock(&props_svc_read_notify_lock);

	return ret;
}

static void props_svc_read_notify_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_NOTIFY;

	ARG_UNUSED(attr);

	printk("read_notify notifications %s\n", enabled ? "enabled" : "disabled");

	props_svc_read_notify_on_ccc(enabled);
}

static ssize_t props_svc_read_indicate_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					    void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	props_svc_read_indicate_on_read();

	k_mutex_lock(&props_svc_read_indicate_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, props_svc_read_indicate_value,
				sizeof(props_svc_read_indicate_value));
	k_mutex_unlock(&props_svc_read_indicate_lock);

	return ret;
}

static void props_svc_read_indicate_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_INDICATE;

	ARG_UNUSED(attr);

	printk("read_indicate indications %s\n", enabled ? "enabled" : "disabled");

	props_svc_read_indicate_on_ccc(enabled);
}

static ssize_t props_svc_rw_notify_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	props_svc_rw_notify_on_read();

	k_mutex_lock(&props_svc_rw_notify_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, props_svc_rw_notify_value,
				sizeof(props_svc_rw_notify_value));
	k_mutex_unlock(&props_svc_rw_notify_lock);

	return ret;
}

static ssize_t props_svc_rw_notify_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					 const void *buf, uint16_t len, uint16_t offset,
					 uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(props_svc_rw_notify_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&props_svc_rw_notify_lock, K_FOREVER);
	memcpy(props_svc_rw_notify_value + offset, buf, len);
	k_mutex_unlock(&props_svc_rw_notify_lock);

	props_svc_rw_notify_on_write(props_svc_rw_notify_value, sizeof(props_svc_rw_notify_value));

	return len;
}

static void props_svc_rw_notify_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_NOTIFY;

	ARG_UNUSED(attr);

	printk("rw_notify notifications %s\n", enabled ? "enabled" : "disabled");

	props_svc_rw_notify_on_ccc(enabled);
}

static ssize_t props_svc_rw_indicate_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					  void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	props_svc_rw_indicate_on_read();

	k_mutex_lock(&props_svc_rw_indicate_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, props_svc_rw_indicate_value,
				sizeof(props_svc_rw_indicate_value));
	k_mutex_unlock(&props_svc_rw_indicate_lock);

	return ret;
}

static ssize_t props_svc_rw_indicate_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					   const void *buf, uint16_t len, uint16_t offset,
					   uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(props_svc_rw_indicate_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&props_svc_rw_indicate_lock, K_FOREVER);
	memcpy(props_svc_rw_indicate_value + offset, buf, len);
	k_mutex_unlock(&props_svc_rw_indicate_lock);

	props_svc_rw_indicate_on_write(props_svc_rw_indicate_value,
				       sizeof(props_svc_rw_indicate_value));

	return len;
}

static void props_svc_rw_indicate_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_INDICATE;

	ARG_UNUSED(attr);

	printk("rw_indicate indications %s\n", enabled ? "enabled" : "disabled");

	props_svc_rw_indicate_on_ccc(enabled);
}

static ssize_t props_svc_wwr_notify_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					  const void *buf, uint16_t len, uint16_t offset,
					  uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(props_svc_wwr_notify_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&props_svc_wwr_notify_lock, K_FOREVER);
	memcpy(props_svc_wwr_notify_value + offset, buf, len);
	k_mutex_unlock(&props_svc_wwr_notify_lock);

	props_svc_wwr_notify_on_write(props_svc_wwr_notify_value,
				      sizeof(props_svc_wwr_notify_value));

	return len;
}

static void props_svc_wwr_notify_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_NOTIFY;

	ARG_UNUSED(attr);

	printk("wwr_notify notifications %s\n", enabled ? "enabled" : "disabled");

	props_svc_wwr_notify_on_ccc(enabled);
}

static ssize_t props_svc_broadcast_chrc_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					     void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	props_svc_broadcast_chrc_on_read();

	k_mutex_lock(&props_svc_broadcast_chrc_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, props_svc_broadcast_chrc_value,
				sizeof(props_svc_broadcast_chrc_value));
	k_mutex_unlock(&props_svc_broadcast_chrc_lock);

	return ret;
}

static ssize_t props_svc_signed_rw_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	props_svc_signed_rw_on_read();

	k_mutex_lock(&props_svc_signed_rw_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, props_svc_signed_rw_value,
				sizeof(props_svc_signed_rw_value));
	k_mutex_unlock(&props_svc_signed_rw_lock);

	return ret;
}

static ssize_t props_svc_signed_rw_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					 const void *buf, uint16_t len, uint16_t offset,
					 uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(props_svc_signed_rw_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&props_svc_signed_rw_lock, K_FOREVER);
	memcpy(props_svc_signed_rw_value + offset, buf, len);
	k_mutex_unlock(&props_svc_signed_rw_lock);

	props_svc_signed_rw_on_write(props_svc_signed_rw_value, sizeof(props_svc_signed_rw_value));

	return len;
}

static ssize_t props_svc_ext_props_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	props_svc_ext_props_on_read();

	k_mutex_lock(&props_svc_ext_props_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, props_svc_ext_props_value,
				sizeof(props_svc_ext_props_value));
	k_mutex_unlock(&props_svc_ext_props_lock);

	return ret;
}

static ssize_t props_svc_ext_props_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					 const void *buf, uint16_t len, uint16_t offset,
					 uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(props_svc_ext_props_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&props_svc_ext_props_lock, K_FOREVER);
	memcpy(props_svc_ext_props_value + offset, buf, len);
	k_mutex_unlock(&props_svc_ext_props_lock);

	props_svc_ext_props_on_write(props_svc_ext_props_value, sizeof(props_svc_ext_props_value));

	return len;
}

static ssize_t props_svc_big_value_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	props_svc_big_value_on_read();

	k_mutex_lock(&props_svc_big_value_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, props_svc_big_value_value,
				sizeof(props_svc_big_value_value));
	k_mutex_unlock(&props_svc_big_value_lock);

	return ret;
}

static ssize_t props_svc_big_value_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					 const void *buf, uint16_t len, uint16_t offset,
					 uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(props_svc_big_value_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&props_svc_big_value_lock, K_FOREVER);
	memcpy(props_svc_big_value_value + offset, buf, len);
	k_mutex_unlock(&props_svc_big_value_lock);

	props_svc_big_value_on_write(props_svc_big_value_value, sizeof(props_svc_big_value_value));

	return len;
}

/* ------------------------------------------------------------------------- */
/* Application hooks (weak defaults; override in your own sources)           */
/* ------------------------------------------------------------------------- */

__weak void props_svc_read_only_on_read(void)
{
}

__weak void props_svc_write_only_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

__weak void props_svc_wwr_only_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

__weak void props_svc_read_write_on_read(void)
{
}
__weak void props_svc_read_write_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

__weak void props_svc_notify_only_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

__weak void props_svc_indicate_only_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

__weak void props_svc_read_notify_on_read(void)
{
}
__weak void props_svc_read_notify_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

__weak void props_svc_read_indicate_on_read(void)
{
}
__weak void props_svc_read_indicate_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

__weak void props_svc_rw_notify_on_read(void)
{
}
__weak void props_svc_rw_notify_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}
__weak void props_svc_rw_notify_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

__weak void props_svc_rw_indicate_on_read(void)
{
}
__weak void props_svc_rw_indicate_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}
__weak void props_svc_rw_indicate_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

__weak void props_svc_wwr_notify_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}
__weak void props_svc_wwr_notify_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

__weak void props_svc_broadcast_chrc_on_read(void)
{
}

__weak void props_svc_signed_rw_on_read(void)
{
}
__weak void props_svc_signed_rw_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

__weak void props_svc_ext_props_on_read(void)
{
}
__weak void props_svc_ext_props_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

__weak void props_svc_big_value_on_read(void)
{
}
__weak void props_svc_big_value_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

/* ------------------------------------------------------------------------- */
/* Push helpers                                                              */
/* ------------------------------------------------------------------------- */

int props_svc_notify_only_notify(const uint8_t *data, uint16_t len)
{
	int err;

	err = props_svc_notify_only_set(data, len);
	if (err) {
		return err;
	}

	return bt_gatt_notify_uuid(NULL, PROPS_SVC_NOTIFY_ONLY_UUID, NULL,
				   props_svc_notify_only_value, len);
}

static struct bt_gatt_indicate_params props_svc_indicate_only_ind_params;

int props_svc_indicate_only_indicate(const uint8_t *data, uint16_t len)
{
	int err;

	err = props_svc_indicate_only_set(data, len);
	if (err) {
		return err;
	}

	props_svc_indicate_only_ind_params.uuid = PROPS_SVC_INDICATE_ONLY_UUID;
	props_svc_indicate_only_ind_params.attr = NULL;
	props_svc_indicate_only_ind_params.data = props_svc_indicate_only_value;
	props_svc_indicate_only_ind_params.len = len;

	return bt_gatt_indicate(NULL, &props_svc_indicate_only_ind_params);
}

int props_svc_read_notify_notify(const uint8_t *data, uint16_t len)
{
	int err;

	err = props_svc_read_notify_set(data, len);
	if (err) {
		return err;
	}

	return bt_gatt_notify_uuid(NULL, PROPS_SVC_READ_NOTIFY_UUID, NULL,
				   props_svc_read_notify_value, len);
}

static struct bt_gatt_indicate_params props_svc_read_indicate_ind_params;

int props_svc_read_indicate_indicate(const uint8_t *data, uint16_t len)
{
	int err;

	err = props_svc_read_indicate_set(data, len);
	if (err) {
		return err;
	}

	props_svc_read_indicate_ind_params.uuid = PROPS_SVC_READ_INDICATE_UUID;
	props_svc_read_indicate_ind_params.attr = NULL;
	props_svc_read_indicate_ind_params.data = props_svc_read_indicate_value;
	props_svc_read_indicate_ind_params.len = len;

	return bt_gatt_indicate(NULL, &props_svc_read_indicate_ind_params);
}

int props_svc_rw_notify_notify(const uint8_t *data, uint16_t len)
{
	int err;

	err = props_svc_rw_notify_set(data, len);
	if (err) {
		return err;
	}

	return bt_gatt_notify_uuid(NULL, PROPS_SVC_RW_NOTIFY_UUID, NULL, props_svc_rw_notify_value,
				   len);
}

static struct bt_gatt_indicate_params props_svc_rw_indicate_ind_params;

int props_svc_rw_indicate_indicate(const uint8_t *data, uint16_t len)
{
	int err;

	err = props_svc_rw_indicate_set(data, len);
	if (err) {
		return err;
	}

	props_svc_rw_indicate_ind_params.uuid = PROPS_SVC_RW_INDICATE_UUID;
	props_svc_rw_indicate_ind_params.attr = NULL;
	props_svc_rw_indicate_ind_params.data = props_svc_rw_indicate_value;
	props_svc_rw_indicate_ind_params.len = len;

	return bt_gatt_indicate(NULL, &props_svc_rw_indicate_ind_params);
}

int props_svc_wwr_notify_notify(const uint8_t *data, uint16_t len)
{
	int err;

	err = props_svc_wwr_notify_set(data, len);
	if (err) {
		return err;
	}

	return bt_gatt_notify_uuid(NULL, PROPS_SVC_WWR_NOTIFY_UUID, NULL,
				   props_svc_wwr_notify_value, len);
}

/* ------------------------------------------------------------------------- */
/* Service declaration                                                       */
/* ------------------------------------------------------------------------- */

/* clang-format off */
BT_GATT_SERVICE_DEFINE(props_svc,
	BT_GATT_PRIMARY_SERVICE(PROPS_SVC_UUID),

	/* read_only: read */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_READ_ONLY_UUID,
			       BT_GATT_CHRC_READ,
			       BT_GATT_PERM_READ,
			       props_svc_read_only_read,
			       NULL,
			       props_svc_read_only_value),

	/* write_only: write */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_WRITE_ONLY_UUID,
			       BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_WRITE,
			       NULL,
			       props_svc_write_only_write,
			       props_svc_write_only_value),

	/* wwr_only: write_without_response */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_WWR_ONLY_UUID,
			       BT_GATT_CHRC_WRITE_WITHOUT_RESP,
			       BT_GATT_PERM_WRITE,
			       NULL,
			       props_svc_wwr_only_write,
			       props_svc_wwr_only_value),

	/* read_write: read, write */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_READ_WRITE_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE,
			       props_svc_read_write_read,
			       props_svc_read_write_write,
			       props_svc_read_write_value),

	/* notify_only: notify */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_NOTIFY_ONLY_UUID,
			       BT_GATT_CHRC_NOTIFY,
			       BT_GATT_PERM_NONE,
			       NULL,
			       NULL,
			       props_svc_notify_only_value),
	BT_GATT_CCC(props_svc_notify_only_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* indicate_only: indicate */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_INDICATE_ONLY_UUID,
			       BT_GATT_CHRC_INDICATE,
			       BT_GATT_PERM_NONE,
			       NULL,
			       NULL,
			       props_svc_indicate_only_value),
	BT_GATT_CCC(props_svc_indicate_only_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* read_notify: read, notify */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_READ_NOTIFY_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_NOTIFY,
			       BT_GATT_PERM_READ,
			       props_svc_read_notify_read,
			       NULL,
			       props_svc_read_notify_value),
	BT_GATT_CCC(props_svc_read_notify_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* read_indicate: read, indicate */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_READ_INDICATE_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_INDICATE,
			       BT_GATT_PERM_READ,
			       props_svc_read_indicate_read,
			       NULL,
			       props_svc_read_indicate_value),
	BT_GATT_CCC(props_svc_read_indicate_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* rw_notify: read, write, notify */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_RW_NOTIFY_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE | BT_GATT_CHRC_NOTIFY,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE,
			       props_svc_rw_notify_read,
			       props_svc_rw_notify_write,
			       props_svc_rw_notify_value),
	BT_GATT_CCC(props_svc_rw_notify_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* rw_indicate: read, write, indicate */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_RW_INDICATE_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE | BT_GATT_CHRC_INDICATE,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE,
			       props_svc_rw_indicate_read,
			       props_svc_rw_indicate_write,
			       props_svc_rw_indicate_value),
	BT_GATT_CCC(props_svc_rw_indicate_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* wwr_notify: write_without_response, notify */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_WWR_NOTIFY_UUID,
			       BT_GATT_CHRC_WRITE_WITHOUT_RESP | BT_GATT_CHRC_NOTIFY,
			       BT_GATT_PERM_WRITE,
			       NULL,
			       props_svc_wwr_notify_write,
			       props_svc_wwr_notify_value),
	BT_GATT_CCC(props_svc_wwr_notify_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* broadcast_chrc: broadcast, read */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_BROADCAST_CHRC_UUID,
			       BT_GATT_CHRC_BROADCAST | BT_GATT_CHRC_READ,
			       BT_GATT_PERM_READ,
			       props_svc_broadcast_chrc_read,
			       NULL,
			       props_svc_broadcast_chrc_value),

	/* signed_rw: authenticated_signed_writes, read, write */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_SIGNED_RW_UUID,
			       BT_GATT_CHRC_AUTH | BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE,
			       props_svc_signed_rw_read,
			       props_svc_signed_rw_write,
			       props_svc_signed_rw_value),

	/* ext_props: read, write, extended_properties */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_EXT_PROPS_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE | BT_GATT_CHRC_EXT_PROP,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE | BT_GATT_PERM_PREPARE_WRITE,
			       props_svc_ext_props_read,
			       props_svc_ext_props_write,
			       props_svc_ext_props_value),
	BT_GATT_CEP(&props_svc_ext_props_cep),

	/* big_value: read, write */
	BT_GATT_CHARACTERISTIC(PROPS_SVC_BIG_VALUE_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE,
			       props_svc_big_value_read,
			       props_svc_big_value_write,
			       props_svc_big_value_value),
);
/* clang-format on */
