/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_full GATT service public API (sec_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit.
 */

#ifndef BLE_GATT_GENERATOR_SEC_SVC_H_
#define BLE_GATT_GENERATOR_SEC_SVC_H_

#include <stdint.h>

#include <zephyr/bluetooth/uuid.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @defgroup sec_svc sec_svc service
 *  @brief Generated helpers for the sec_svc GATT service.
 *  @{
 */

/* Service and characteristic UUIDs. */
#define SEC_SVC_UUID                                                                               \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde20))
#define SEC_SVC_ENC_READ_UUID                                                                      \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde21))
#define SEC_SVC_ENC_WRITE_UUID                                                                     \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde22))
#define SEC_SVC_ENC_RW_UUID                                                                        \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde23))
#define SEC_SVC_AUTH_READ_UUID                                                                     \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde24))
#define SEC_SVC_AUTH_RW_UUID                                                                       \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde25))
#define SEC_SVC_LESC_RW_UUID                                                                       \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde26))
#define SEC_SVC_ENC_NOTIFY_UUID                                                                    \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde27))
#define SEC_SVC_AUTH_INDICATE_UUID                                                                 \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde28))

/* Characteristic value sizes in bytes. */
#define SEC_SVC_ENC_READ_SIZE      8
#define SEC_SVC_ENC_WRITE_SIZE     8
#define SEC_SVC_ENC_RW_SIZE        8
#define SEC_SVC_AUTH_READ_SIZE     8
#define SEC_SVC_AUTH_RW_SIZE       8
#define SEC_SVC_LESC_RW_SIZE       8
#define SEC_SVC_ENC_NOTIFY_SIZE    8
#define SEC_SVC_AUTH_INDICATE_SIZE 8

/** @brief Set the enc_read characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_ENC_READ_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_enc_read_set(const uint8_t *data, uint16_t len);

/** @brief Get the enc_read characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_ENC_READ_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_enc_read_get(uint8_t *data, uint16_t len);

/** @brief Set the enc_write characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_ENC_WRITE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_enc_write_set(const uint8_t *data, uint16_t len);

/** @brief Get the enc_write characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_ENC_WRITE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_enc_write_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes enc_write.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void sec_svc_enc_write_on_write(const uint8_t *data, uint16_t len);

/** @brief Set the enc_rw characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_ENC_RW_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_enc_rw_set(const uint8_t *data, uint16_t len);

/** @brief Get the enc_rw characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_ENC_RW_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_enc_rw_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes enc_rw.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void sec_svc_enc_rw_on_write(const uint8_t *data, uint16_t len);

/** @brief Set the auth_read characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_AUTH_READ_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_auth_read_set(const uint8_t *data, uint16_t len);

/** @brief Get the auth_read characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_AUTH_READ_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_auth_read_get(uint8_t *data, uint16_t len);

/** @brief Set the auth_rw characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_AUTH_RW_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_auth_rw_set(const uint8_t *data, uint16_t len);

/** @brief Get the auth_rw characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_AUTH_RW_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_auth_rw_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes auth_rw.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void sec_svc_auth_rw_on_write(const uint8_t *data, uint16_t len);

/** @brief Set the lesc_rw characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_LESC_RW_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_lesc_rw_set(const uint8_t *data, uint16_t len);

/** @brief Get the lesc_rw characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_LESC_RW_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_lesc_rw_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes lesc_rw.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void sec_svc_lesc_rw_on_write(const uint8_t *data, uint16_t len);

/** @brief Set the enc_notify characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_ENC_NOTIFY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_enc_notify_set(const uint8_t *data, uint16_t len);

/** @brief Get the enc_notify characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_ENC_NOTIFY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_enc_notify_get(uint8_t *data, uint16_t len);

/** @brief Update and notify the enc_notify characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_notify_uuid()).
 */
int sec_svc_enc_notify_notify(const uint8_t *data, uint16_t len);

/** @brief Set the auth_indicate characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_AUTH_INDICATE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_auth_indicate_set(const uint8_t *data, uint16_t len);

/** @brief Get the auth_indicate characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              SEC_SVC_AUTH_INDICATE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sec_svc_auth_indicate_get(uint8_t *data, uint16_t len);

/** @brief Update and indicate the auth_indicate characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_indicate()).
 */
int sec_svc_auth_indicate_indicate(const uint8_t *data, uint16_t len);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* BLE_GATT_GENERATOR_SEC_SVC_H_ */
