/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_full GATT service implementation (sec_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit. Put application logic in
 *  main.c or your own sources and call the public helpers declared in
 *  sec_svc_service.h.
 */

#include <errno.h>
#include <stdint.h>
#include <string.h>

#include <zephyr/kernel.h>
#include <zephyr/sys/printk.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>

#include "sec_svc_service.h"

/* ------------------------------------------------------------------------- */
/* Characteristic value storage                                              */
/* ------------------------------------------------------------------------- */

static uint8_t sec_svc_enc_read_value[SEC_SVC_ENC_READ_SIZE];
static K_MUTEX_DEFINE(sec_svc_enc_read_lock);
static uint8_t sec_svc_enc_write_value[SEC_SVC_ENC_WRITE_SIZE];
static K_MUTEX_DEFINE(sec_svc_enc_write_lock);
static uint8_t sec_svc_enc_rw_value[SEC_SVC_ENC_RW_SIZE];
static K_MUTEX_DEFINE(sec_svc_enc_rw_lock);
static uint8_t sec_svc_auth_read_value[SEC_SVC_AUTH_READ_SIZE];
static K_MUTEX_DEFINE(sec_svc_auth_read_lock);
static uint8_t sec_svc_auth_rw_value[SEC_SVC_AUTH_RW_SIZE];
static K_MUTEX_DEFINE(sec_svc_auth_rw_lock);
static uint8_t sec_svc_lesc_rw_value[SEC_SVC_LESC_RW_SIZE];
static K_MUTEX_DEFINE(sec_svc_lesc_rw_lock);
static uint8_t sec_svc_enc_notify_value[SEC_SVC_ENC_NOTIFY_SIZE];
static K_MUTEX_DEFINE(sec_svc_enc_notify_lock);
static uint8_t sec_svc_auth_indicate_value[SEC_SVC_AUTH_INDICATE_SIZE];
static K_MUTEX_DEFINE(sec_svc_auth_indicate_lock);

/* ------------------------------------------------------------------------- */
/* Static descriptor payloads                                                */
/* ------------------------------------------------------------------------- */

/* ------------------------------------------------------------------------- */
/* Thread-safe accessors                                                     */
/* ------------------------------------------------------------------------- */

int sec_svc_enc_read_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(sec_svc_enc_read_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_enc_read_lock, K_FOREVER);
	memcpy(sec_svc_enc_read_value, data, len);
	k_mutex_unlock(&sec_svc_enc_read_lock);

	return 0;
}

int sec_svc_enc_read_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(sec_svc_enc_read_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_enc_read_lock, K_FOREVER);
	memcpy(data, sec_svc_enc_read_value, MIN(len, sizeof(sec_svc_enc_read_value)));
	k_mutex_unlock(&sec_svc_enc_read_lock);

	return 0;
}

int sec_svc_enc_write_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(sec_svc_enc_write_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_enc_write_lock, K_FOREVER);
	memcpy(sec_svc_enc_write_value, data, len);
	k_mutex_unlock(&sec_svc_enc_write_lock);

	return 0;
}

int sec_svc_enc_write_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(sec_svc_enc_write_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_enc_write_lock, K_FOREVER);
	memcpy(data, sec_svc_enc_write_value, MIN(len, sizeof(sec_svc_enc_write_value)));
	k_mutex_unlock(&sec_svc_enc_write_lock);

	return 0;
}

int sec_svc_enc_rw_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(sec_svc_enc_rw_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_enc_rw_lock, K_FOREVER);
	memcpy(sec_svc_enc_rw_value, data, len);
	k_mutex_unlock(&sec_svc_enc_rw_lock);

	return 0;
}

int sec_svc_enc_rw_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(sec_svc_enc_rw_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_enc_rw_lock, K_FOREVER);
	memcpy(data, sec_svc_enc_rw_value, MIN(len, sizeof(sec_svc_enc_rw_value)));
	k_mutex_unlock(&sec_svc_enc_rw_lock);

	return 0;
}

int sec_svc_auth_read_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(sec_svc_auth_read_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_auth_read_lock, K_FOREVER);
	memcpy(sec_svc_auth_read_value, data, len);
	k_mutex_unlock(&sec_svc_auth_read_lock);

	return 0;
}

int sec_svc_auth_read_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(sec_svc_auth_read_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_auth_read_lock, K_FOREVER);
	memcpy(data, sec_svc_auth_read_value, MIN(len, sizeof(sec_svc_auth_read_value)));
	k_mutex_unlock(&sec_svc_auth_read_lock);

	return 0;
}

int sec_svc_auth_rw_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(sec_svc_auth_rw_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_auth_rw_lock, K_FOREVER);
	memcpy(sec_svc_auth_rw_value, data, len);
	k_mutex_unlock(&sec_svc_auth_rw_lock);

	return 0;
}

int sec_svc_auth_rw_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(sec_svc_auth_rw_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_auth_rw_lock, K_FOREVER);
	memcpy(data, sec_svc_auth_rw_value, MIN(len, sizeof(sec_svc_auth_rw_value)));
	k_mutex_unlock(&sec_svc_auth_rw_lock);

	return 0;
}

int sec_svc_lesc_rw_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(sec_svc_lesc_rw_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_lesc_rw_lock, K_FOREVER);
	memcpy(sec_svc_lesc_rw_value, data, len);
	k_mutex_unlock(&sec_svc_lesc_rw_lock);

	return 0;
}

int sec_svc_lesc_rw_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(sec_svc_lesc_rw_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_lesc_rw_lock, K_FOREVER);
	memcpy(data, sec_svc_lesc_rw_value, MIN(len, sizeof(sec_svc_lesc_rw_value)));
	k_mutex_unlock(&sec_svc_lesc_rw_lock);

	return 0;
}

int sec_svc_enc_notify_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(sec_svc_enc_notify_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_enc_notify_lock, K_FOREVER);
	memcpy(sec_svc_enc_notify_value, data, len);
	k_mutex_unlock(&sec_svc_enc_notify_lock);

	return 0;
}

int sec_svc_enc_notify_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(sec_svc_enc_notify_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_enc_notify_lock, K_FOREVER);
	memcpy(data, sec_svc_enc_notify_value, MIN(len, sizeof(sec_svc_enc_notify_value)));
	k_mutex_unlock(&sec_svc_enc_notify_lock);

	return 0;
}

int sec_svc_auth_indicate_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(sec_svc_auth_indicate_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_auth_indicate_lock, K_FOREVER);
	memcpy(sec_svc_auth_indicate_value, data, len);
	k_mutex_unlock(&sec_svc_auth_indicate_lock);

	return 0;
}

int sec_svc_auth_indicate_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(sec_svc_auth_indicate_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sec_svc_auth_indicate_lock, K_FOREVER);
	memcpy(data, sec_svc_auth_indicate_value, MIN(len, sizeof(sec_svc_auth_indicate_value)));
	k_mutex_unlock(&sec_svc_auth_indicate_lock);

	return 0;
}

/* ------------------------------------------------------------------------- */
/* GATT attribute callbacks                                                  */
/* ------------------------------------------------------------------------- */

static ssize_t sec_svc_enc_read_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				     void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	sec_svc_enc_read_on_read();

	k_mutex_lock(&sec_svc_enc_read_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, sec_svc_enc_read_value,
				sizeof(sec_svc_enc_read_value));
	k_mutex_unlock(&sec_svc_enc_read_lock);

	return ret;
}

static ssize_t sec_svc_enc_write_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				       const void *buf, uint16_t len, uint16_t offset,
				       uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(sec_svc_enc_write_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&sec_svc_enc_write_lock, K_FOREVER);
	memcpy(sec_svc_enc_write_value + offset, buf, len);
	k_mutex_unlock(&sec_svc_enc_write_lock);

	sec_svc_enc_write_on_write(sec_svc_enc_write_value, sizeof(sec_svc_enc_write_value));

	return len;
}

static ssize_t sec_svc_enc_rw_read(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf,
				   uint16_t len, uint16_t offset)
{
	ssize_t ret;

	sec_svc_enc_rw_on_read();

	k_mutex_lock(&sec_svc_enc_rw_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, sec_svc_enc_rw_value,
				sizeof(sec_svc_enc_rw_value));
	k_mutex_unlock(&sec_svc_enc_rw_lock);

	return ret;
}

static ssize_t sec_svc_enc_rw_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				    const void *buf, uint16_t len, uint16_t offset, uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(sec_svc_enc_rw_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&sec_svc_enc_rw_lock, K_FOREVER);
	memcpy(sec_svc_enc_rw_value + offset, buf, len);
	k_mutex_unlock(&sec_svc_enc_rw_lock);

	sec_svc_enc_rw_on_write(sec_svc_enc_rw_value, sizeof(sec_svc_enc_rw_value));

	return len;
}

static ssize_t sec_svc_auth_read_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				      void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	sec_svc_auth_read_on_read();

	k_mutex_lock(&sec_svc_auth_read_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, sec_svc_auth_read_value,
				sizeof(sec_svc_auth_read_value));
	k_mutex_unlock(&sec_svc_auth_read_lock);

	return ret;
}

static ssize_t sec_svc_auth_rw_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				    void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	sec_svc_auth_rw_on_read();

	k_mutex_lock(&sec_svc_auth_rw_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, sec_svc_auth_rw_value,
				sizeof(sec_svc_auth_rw_value));
	k_mutex_unlock(&sec_svc_auth_rw_lock);

	return ret;
}

static ssize_t sec_svc_auth_rw_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				     const void *buf, uint16_t len, uint16_t offset, uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(sec_svc_auth_rw_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&sec_svc_auth_rw_lock, K_FOREVER);
	memcpy(sec_svc_auth_rw_value + offset, buf, len);
	k_mutex_unlock(&sec_svc_auth_rw_lock);

	sec_svc_auth_rw_on_write(sec_svc_auth_rw_value, sizeof(sec_svc_auth_rw_value));

	return len;
}

static ssize_t sec_svc_lesc_rw_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				    void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	sec_svc_lesc_rw_on_read();

	k_mutex_lock(&sec_svc_lesc_rw_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, sec_svc_lesc_rw_value,
				sizeof(sec_svc_lesc_rw_value));
	k_mutex_unlock(&sec_svc_lesc_rw_lock);

	return ret;
}

static ssize_t sec_svc_lesc_rw_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				     const void *buf, uint16_t len, uint16_t offset, uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(sec_svc_lesc_rw_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&sec_svc_lesc_rw_lock, K_FOREVER);
	memcpy(sec_svc_lesc_rw_value + offset, buf, len);
	k_mutex_unlock(&sec_svc_lesc_rw_lock);

	sec_svc_lesc_rw_on_write(sec_svc_lesc_rw_value, sizeof(sec_svc_lesc_rw_value));

	return len;
}

static ssize_t sec_svc_enc_notify_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				       void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	sec_svc_enc_notify_on_read();

	k_mutex_lock(&sec_svc_enc_notify_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, sec_svc_enc_notify_value,
				sizeof(sec_svc_enc_notify_value));
	k_mutex_unlock(&sec_svc_enc_notify_lock);

	return ret;
}

static void sec_svc_enc_notify_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_NOTIFY;

	ARG_UNUSED(attr);

	printk("enc_notify notifications %s\n", enabled ? "enabled" : "disabled");

	sec_svc_enc_notify_on_ccc(enabled);
}

static ssize_t sec_svc_auth_indicate_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					  void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	sec_svc_auth_indicate_on_read();

	k_mutex_lock(&sec_svc_auth_indicate_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, sec_svc_auth_indicate_value,
				sizeof(sec_svc_auth_indicate_value));
	k_mutex_unlock(&sec_svc_auth_indicate_lock);

	return ret;
}

static void sec_svc_auth_indicate_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_INDICATE;

	ARG_UNUSED(attr);

	printk("auth_indicate indications %s\n", enabled ? "enabled" : "disabled");

	sec_svc_auth_indicate_on_ccc(enabled);
}

/* ------------------------------------------------------------------------- */
/* Application hooks (weak defaults; override in your own sources)           */
/* ------------------------------------------------------------------------- */

__weak void sec_svc_enc_read_on_read(void)
{
}

__weak void sec_svc_enc_write_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

__weak void sec_svc_enc_rw_on_read(void)
{
}
__weak void sec_svc_enc_rw_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

__weak void sec_svc_auth_read_on_read(void)
{
}

__weak void sec_svc_auth_rw_on_read(void)
{
}
__weak void sec_svc_auth_rw_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

__weak void sec_svc_lesc_rw_on_read(void)
{
}
__weak void sec_svc_lesc_rw_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

__weak void sec_svc_enc_notify_on_read(void)
{
}
__weak void sec_svc_enc_notify_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

__weak void sec_svc_auth_indicate_on_read(void)
{
}
__weak void sec_svc_auth_indicate_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

/* ------------------------------------------------------------------------- */
/* Push helpers                                                              */
/* ------------------------------------------------------------------------- */

int sec_svc_enc_notify_notify(const uint8_t *data, uint16_t len)
{
	int err;

	err = sec_svc_enc_notify_set(data, len);
	if (err) {
		return err;
	}

	return bt_gatt_notify_uuid(NULL, SEC_SVC_ENC_NOTIFY_UUID, NULL, sec_svc_enc_notify_value,
				   len);
}

static struct bt_gatt_indicate_params sec_svc_auth_indicate_ind_params;

int sec_svc_auth_indicate_indicate(const uint8_t *data, uint16_t len)
{
	int err;

	err = sec_svc_auth_indicate_set(data, len);
	if (err) {
		return err;
	}

	sec_svc_auth_indicate_ind_params.uuid = SEC_SVC_AUTH_INDICATE_UUID;
	sec_svc_auth_indicate_ind_params.attr = NULL;
	sec_svc_auth_indicate_ind_params.data = sec_svc_auth_indicate_value;
	sec_svc_auth_indicate_ind_params.len = len;

	return bt_gatt_indicate(NULL, &sec_svc_auth_indicate_ind_params);
}

/* ------------------------------------------------------------------------- */
/* Service declaration                                                       */
/* ------------------------------------------------------------------------- */

/* clang-format off */
BT_GATT_SERVICE_DEFINE(sec_svc,
	BT_GATT_PRIMARY_SERVICE(SEC_SVC_UUID),

	/* enc_read: read */
	BT_GATT_CHARACTERISTIC(SEC_SVC_ENC_READ_UUID,
			       BT_GATT_CHRC_READ,
			       BT_GATT_PERM_READ_ENCRYPT,
			       sec_svc_enc_read_read,
			       NULL,
			       sec_svc_enc_read_value),

	/* enc_write: write */
	BT_GATT_CHARACTERISTIC(SEC_SVC_ENC_WRITE_UUID,
			       BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_WRITE_ENCRYPT,
			       NULL,
			       sec_svc_enc_write_write,
			       sec_svc_enc_write_value),

	/* enc_rw: read, write */
	BT_GATT_CHARACTERISTIC(SEC_SVC_ENC_RW_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ_ENCRYPT | BT_GATT_PERM_WRITE_ENCRYPT,
			       sec_svc_enc_rw_read,
			       sec_svc_enc_rw_write,
			       sec_svc_enc_rw_value),

	/* auth_read: read */
	BT_GATT_CHARACTERISTIC(SEC_SVC_AUTH_READ_UUID,
			       BT_GATT_CHRC_READ,
			       BT_GATT_PERM_READ_AUTHEN,
			       sec_svc_auth_read_read,
			       NULL,
			       sec_svc_auth_read_value),

	/* auth_rw: read, write */
	BT_GATT_CHARACTERISTIC(SEC_SVC_AUTH_RW_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ_AUTHEN | BT_GATT_PERM_WRITE_AUTHEN,
			       sec_svc_auth_rw_read,
			       sec_svc_auth_rw_write,
			       sec_svc_auth_rw_value),

	/* lesc_rw: read, write */
	BT_GATT_CHARACTERISTIC(SEC_SVC_LESC_RW_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ_LESC | BT_GATT_PERM_WRITE_LESC,
			       sec_svc_lesc_rw_read,
			       sec_svc_lesc_rw_write,
			       sec_svc_lesc_rw_value),

	/* enc_notify: read, notify */
	BT_GATT_CHARACTERISTIC(SEC_SVC_ENC_NOTIFY_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_NOTIFY,
			       BT_GATT_PERM_READ_ENCRYPT,
			       sec_svc_enc_notify_read,
			       NULL,
			       sec_svc_enc_notify_value),
	BT_GATT_CCC(sec_svc_enc_notify_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* auth_indicate: read, indicate */
	BT_GATT_CHARACTERISTIC(SEC_SVC_AUTH_INDICATE_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_INDICATE,
			       BT_GATT_PERM_READ_AUTHEN,
			       sec_svc_auth_indicate_read,
			       NULL,
			       sec_svc_auth_indicate_value),
	BT_GATT_CCC(sec_svc_auth_indicate_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),
);
/* clang-format on */
