/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_multi GATT service public API (device_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit.
 */

#ifndef BLE_GATT_GENERATOR_DEVICE_SVC_H_
#define BLE_GATT_GENERATOR_DEVICE_SVC_H_

#include <stdint.h>

#include <zephyr/bluetooth/uuid.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @defgroup device_svc device_svc service
 *  @brief Generated helpers for the device_svc GATT service.
 *  @{
 */

/* Service and characteristic UUIDs. */
#define DEVICE_SVC_UUID                                                                            \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde10))
#define DEVICE_SVC_DEVICE_NAME_UUID                                                                \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde11))
#define DEVICE_SVC_REBOOT_UUID                                                                     \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde12))
#define DEVICE_SVC_EVENT_FLAG_UUID                                                                 \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcde13))

/* Characteristic value sizes in bytes. */
#define DEVICE_SVC_DEVICE_NAME_SIZE 20
#define DEVICE_SVC_REBOOT_SIZE      1
#define DEVICE_SVC_EVENT_FLAG_SIZE  4

/** @brief Set the device_name characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              DEVICE_SVC_DEVICE_NAME_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int device_svc_device_name_set(const uint8_t *data, uint16_t len);

/** @brief Get the device_name characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              DEVICE_SVC_DEVICE_NAME_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int device_svc_device_name_get(uint8_t *data, uint16_t len);

/** @brief Set the reboot characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              DEVICE_SVC_REBOOT_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int device_svc_reboot_set(const uint8_t *data, uint16_t len);

/** @brief Get the reboot characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              DEVICE_SVC_REBOOT_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int device_svc_reboot_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes reboot.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void device_svc_reboot_on_write(const uint8_t *data, uint16_t len);

/** @brief Set the event_flag characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              DEVICE_SVC_EVENT_FLAG_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int device_svc_event_flag_set(const uint8_t *data, uint16_t len);

/** @brief Get the event_flag characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              DEVICE_SVC_EVENT_FLAG_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int device_svc_event_flag_get(uint8_t *data, uint16_t len);

/** @brief Update and notify the event_flag characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_notify_uuid()).
 */
int device_svc_event_flag_notify(const uint8_t *data, uint16_t len);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* BLE_GATT_GENERATOR_DEVICE_SVC_H_ */
