/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_multi GATT service implementation (device_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit. Put application logic in
 *  main.c or your own sources and call the public helpers declared in
 *  device_svc_service.h.
 */

#include <errno.h>
#include <stdint.h>
#include <string.h>

#include <zephyr/kernel.h>
#include <zephyr/sys/printk.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>

#include "device_svc_service.h"

/* ------------------------------------------------------------------------- */
/* Characteristic value storage                                              */
/* ------------------------------------------------------------------------- */

static uint8_t device_svc_device_name_value[DEVICE_SVC_DEVICE_NAME_SIZE];
static K_MUTEX_DEFINE(device_svc_device_name_lock);
static uint8_t device_svc_reboot_value[DEVICE_SVC_REBOOT_SIZE];
static K_MUTEX_DEFINE(device_svc_reboot_lock);
static uint8_t device_svc_event_flag_value[DEVICE_SVC_EVENT_FLAG_SIZE];
static K_MUTEX_DEFINE(device_svc_event_flag_lock);

/* ------------------------------------------------------------------------- */
/* Static descriptor payloads                                                */
/* ------------------------------------------------------------------------- */

/* ------------------------------------------------------------------------- */
/* Thread-safe accessors                                                     */
/* ------------------------------------------------------------------------- */

int device_svc_device_name_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(device_svc_device_name_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&device_svc_device_name_lock, K_FOREVER);
	memcpy(device_svc_device_name_value, data, len);
	k_mutex_unlock(&device_svc_device_name_lock);

	return 0;
}

int device_svc_device_name_get(uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(device_svc_device_name_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&device_svc_device_name_lock, K_FOREVER);
	memcpy(data, device_svc_device_name_value, len);
	k_mutex_unlock(&device_svc_device_name_lock);

	return 0;
}

int device_svc_reboot_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(device_svc_reboot_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&device_svc_reboot_lock, K_FOREVER);
	memcpy(device_svc_reboot_value, data, len);
	k_mutex_unlock(&device_svc_reboot_lock);

	return 0;
}

int device_svc_reboot_get(uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(device_svc_reboot_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&device_svc_reboot_lock, K_FOREVER);
	memcpy(data, device_svc_reboot_value, len);
	k_mutex_unlock(&device_svc_reboot_lock);

	return 0;
}

int device_svc_event_flag_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(device_svc_event_flag_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&device_svc_event_flag_lock, K_FOREVER);
	memcpy(device_svc_event_flag_value, data, len);
	k_mutex_unlock(&device_svc_event_flag_lock);

	return 0;
}

int device_svc_event_flag_get(uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(device_svc_event_flag_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&device_svc_event_flag_lock, K_FOREVER);
	memcpy(data, device_svc_event_flag_value, len);
	k_mutex_unlock(&device_svc_event_flag_lock);

	return 0;
}

/* ------------------------------------------------------------------------- */
/* GATT attribute callbacks                                                  */
/* ------------------------------------------------------------------------- */

static ssize_t device_svc_device_name_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					   void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	k_mutex_lock(&device_svc_device_name_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, device_svc_device_name_value,
				sizeof(device_svc_device_name_value));
	k_mutex_unlock(&device_svc_device_name_lock);

	return ret;
}

static ssize_t device_svc_reboot_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				       const void *buf, uint16_t len, uint16_t offset,
				       uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(device_svc_reboot_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&device_svc_reboot_lock, K_FOREVER);
	memcpy(device_svc_reboot_value + offset, buf, len);
	k_mutex_unlock(&device_svc_reboot_lock);

	device_svc_reboot_on_write(device_svc_reboot_value, sizeof(device_svc_reboot_value));

	return len;
}

static void device_svc_event_flag_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	ARG_UNUSED(attr);

	printk("event_flag notifications %s\n",
	       value == BT_GATT_CCC_NOTIFY ? "enabled" : "disabled");
}

/* ------------------------------------------------------------------------- */
/* Application hooks (weak defaults; override in your own sources)           */
/* ------------------------------------------------------------------------- */

__weak void device_svc_reboot_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

/* ------------------------------------------------------------------------- */
/* Push helpers                                                              */
/* ------------------------------------------------------------------------- */

int device_svc_event_flag_notify(const uint8_t *data, uint16_t len)
{
	int err;

	err = device_svc_event_flag_set(data, len);
	if (err) {
		return err;
	}

	return bt_gatt_notify_uuid(NULL, DEVICE_SVC_EVENT_FLAG_UUID, NULL,
				   device_svc_event_flag_value, len);
}

/* ------------------------------------------------------------------------- */
/* Service declaration                                                       */
/* ------------------------------------------------------------------------- */

/* clang-format off */
BT_GATT_SERVICE_DEFINE(device_svc,
	BT_GATT_PRIMARY_SERVICE(DEVICE_SVC_UUID),

	/* device_name: read */
	BT_GATT_CHARACTERISTIC(DEVICE_SVC_DEVICE_NAME_UUID,
			       BT_GATT_CHRC_READ,
			       BT_GATT_PERM_READ,
			       device_svc_device_name_read,
			       NULL,
			       device_svc_device_name_value),
	BT_GATT_CUD("Device name", BT_GATT_PERM_READ),

	/* reboot: write */
	BT_GATT_CHARACTERISTIC(DEVICE_SVC_REBOOT_UUID,
			       BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_WRITE,
			       NULL,
			       device_svc_reboot_write,
			       device_svc_reboot_value),

	/* event_flag: notify */
	BT_GATT_CHARACTERISTIC(DEVICE_SVC_EVENT_FLAG_UUID,
			       BT_GATT_CHRC_NOTIFY,
			       BT_GATT_PERM_NONE,
			       NULL,
			       NULL,
			       device_svc_event_flag_value),
	BT_GATT_CCC(device_svc_event_flag_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),
);
/* clang-format on */
