/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_multi GATT service public API (sensor_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit.
 */

#ifndef BLE_GATT_GENERATOR_SENSOR_SVC_H_
#define BLE_GATT_GENERATOR_SENSOR_SVC_H_

#include <stdint.h>

#include <zephyr/bluetooth/uuid.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @defgroup sensor_svc sensor_svc service
 *  @brief Generated helpers for the sensor_svc GATT service.
 *  @{
 */

/* Service and characteristic UUIDs. */
#define SENSOR_SVC_UUID                                                                            \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef0))
#define SENSOR_SVC_TEMPERATURE_UUID                                                                \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef1))
#define SENSOR_SVC_HUMIDITY_UUID                                                                   \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef2))
#define SENSOR_SVC_SAMPLING_RATE_UUID                                                              \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef3))

/* Characteristic value sizes in bytes. */
#define SENSOR_SVC_TEMPERATURE_SIZE   4
#define SENSOR_SVC_HUMIDITY_SIZE      2
#define SENSOR_SVC_SAMPLING_RATE_SIZE 2

/** @brief Set the temperature characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              SENSOR_SVC_TEMPERATURE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sensor_svc_temperature_set(const uint8_t *data, uint16_t len);

/** @brief Get the temperature characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              SENSOR_SVC_TEMPERATURE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sensor_svc_temperature_get(uint8_t *data, uint16_t len);

/** @brief Update and notify the temperature characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_notify_uuid()).
 */
int sensor_svc_temperature_notify(const uint8_t *data, uint16_t len);

/** @brief Set the humidity characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              SENSOR_SVC_HUMIDITY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sensor_svc_humidity_set(const uint8_t *data, uint16_t len);

/** @brief Get the humidity characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              SENSOR_SVC_HUMIDITY_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sensor_svc_humidity_get(uint8_t *data, uint16_t len);

/** @brief Update and indicate the humidity characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_indicate()).
 */
int sensor_svc_humidity_indicate(const uint8_t *data, uint16_t len);

/** @brief Set the sampling_rate characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              SENSOR_SVC_SAMPLING_RATE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sensor_svc_sampling_rate_set(const uint8_t *data, uint16_t len);

/** @brief Get the sampling_rate characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              SENSOR_SVC_SAMPLING_RATE_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int sensor_svc_sampling_rate_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes sampling_rate.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void sensor_svc_sampling_rate_on_write(const uint8_t *data, uint16_t len);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* BLE_GATT_GENERATOR_SENSOR_SVC_H_ */
