/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_multi GATT service implementation (sensor_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit. Put application logic in
 *  main.c or your own sources and call the public helpers declared in
 *  sensor_svc_service.h.
 */

#include <errno.h>
#include <stdint.h>
#include <string.h>

#include <zephyr/kernel.h>
#include <zephyr/sys/printk.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>

#include "sensor_svc_service.h"

/* ------------------------------------------------------------------------- */
/* Characteristic value storage                                              */
/* ------------------------------------------------------------------------- */

static uint8_t sensor_svc_temperature_value[SENSOR_SVC_TEMPERATURE_SIZE];
static K_MUTEX_DEFINE(sensor_svc_temperature_lock);
static uint8_t sensor_svc_humidity_value[SENSOR_SVC_HUMIDITY_SIZE];
static K_MUTEX_DEFINE(sensor_svc_humidity_lock);
static uint8_t sensor_svc_sampling_rate_value[SENSOR_SVC_SAMPLING_RATE_SIZE];
static K_MUTEX_DEFINE(sensor_svc_sampling_rate_lock);

/* ------------------------------------------------------------------------- */
/* Static descriptor payloads                                                */
/* ------------------------------------------------------------------------- */

static const struct bt_gatt_cpf sensor_svc_temperature_cpf = {
	.format = 14,
	.exponent = -2,
	.unit = 10031,
	.name_space = 1,
	.description = 0,
};

/* ------------------------------------------------------------------------- */
/* Thread-safe accessors                                                     */
/* ------------------------------------------------------------------------- */

int sensor_svc_temperature_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(sensor_svc_temperature_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sensor_svc_temperature_lock, K_FOREVER);
	memcpy(sensor_svc_temperature_value, data, len);
	k_mutex_unlock(&sensor_svc_temperature_lock);

	return 0;
}

int sensor_svc_temperature_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(sensor_svc_temperature_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sensor_svc_temperature_lock, K_FOREVER);
	memcpy(data, sensor_svc_temperature_value, MIN(len, sizeof(sensor_svc_temperature_value)));
	k_mutex_unlock(&sensor_svc_temperature_lock);

	return 0;
}

int sensor_svc_humidity_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(sensor_svc_humidity_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sensor_svc_humidity_lock, K_FOREVER);
	memcpy(sensor_svc_humidity_value, data, len);
	k_mutex_unlock(&sensor_svc_humidity_lock);

	return 0;
}

int sensor_svc_humidity_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(sensor_svc_humidity_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sensor_svc_humidity_lock, K_FOREVER);
	memcpy(data, sensor_svc_humidity_value, MIN(len, sizeof(sensor_svc_humidity_value)));
	k_mutex_unlock(&sensor_svc_humidity_lock);

	return 0;
}

int sensor_svc_sampling_rate_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(sensor_svc_sampling_rate_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sensor_svc_sampling_rate_lock, K_FOREVER);
	memcpy(sensor_svc_sampling_rate_value, data, len);
	k_mutex_unlock(&sensor_svc_sampling_rate_lock);

	return 0;
}

int sensor_svc_sampling_rate_get(uint8_t *data, uint16_t len)
{
	if (data == NULL) {
		return -EINVAL;
	}
	if (len > sizeof(sensor_svc_sampling_rate_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&sensor_svc_sampling_rate_lock, K_FOREVER);
	memcpy(data, sensor_svc_sampling_rate_value,
	       MIN(len, sizeof(sensor_svc_sampling_rate_value)));
	k_mutex_unlock(&sensor_svc_sampling_rate_lock);

	return 0;
}

/* ------------------------------------------------------------------------- */
/* GATT attribute callbacks                                                  */
/* ------------------------------------------------------------------------- */

static ssize_t sensor_svc_temperature_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					   void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	sensor_svc_temperature_on_read();

	k_mutex_lock(&sensor_svc_temperature_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, sensor_svc_temperature_value,
				sizeof(sensor_svc_temperature_value));
	k_mutex_unlock(&sensor_svc_temperature_lock);

	return ret;
}

static void sensor_svc_temperature_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_NOTIFY;

	ARG_UNUSED(attr);

	printk("temperature notifications %s\n", enabled ? "enabled" : "disabled");

	sensor_svc_temperature_on_ccc(enabled);
}

static ssize_t sensor_svc_humidity_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	sensor_svc_humidity_on_read();

	k_mutex_lock(&sensor_svc_humidity_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, sensor_svc_humidity_value,
				sizeof(sensor_svc_humidity_value));
	k_mutex_unlock(&sensor_svc_humidity_lock);

	return ret;
}

static void sensor_svc_humidity_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	bool enabled = value == BT_GATT_CCC_INDICATE;

	ARG_UNUSED(attr);

	printk("humidity indications %s\n", enabled ? "enabled" : "disabled");

	sensor_svc_humidity_on_ccc(enabled);
}

static ssize_t sensor_svc_sampling_rate_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					     void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	sensor_svc_sampling_rate_on_read();

	k_mutex_lock(&sensor_svc_sampling_rate_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, sensor_svc_sampling_rate_value,
				sizeof(sensor_svc_sampling_rate_value));
	k_mutex_unlock(&sensor_svc_sampling_rate_lock);

	return ret;
}

static ssize_t sensor_svc_sampling_rate_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
					      const void *buf, uint16_t len, uint16_t offset,
					      uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(sensor_svc_sampling_rate_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&sensor_svc_sampling_rate_lock, K_FOREVER);
	memcpy(sensor_svc_sampling_rate_value + offset, buf, len);
	k_mutex_unlock(&sensor_svc_sampling_rate_lock);

	sensor_svc_sampling_rate_on_write(sensor_svc_sampling_rate_value,
					  sizeof(sensor_svc_sampling_rate_value));

	return len;
}

/* ------------------------------------------------------------------------- */
/* Application hooks (weak defaults; override in your own sources)           */
/* ------------------------------------------------------------------------- */

__weak void sensor_svc_temperature_on_read(void)
{
}
__weak void sensor_svc_temperature_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

__weak void sensor_svc_humidity_on_read(void)
{
}
__weak void sensor_svc_humidity_on_ccc(bool enabled)
{
	ARG_UNUSED(enabled);
}

__weak void sensor_svc_sampling_rate_on_read(void)
{
}
__weak void sensor_svc_sampling_rate_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

/* ------------------------------------------------------------------------- */
/* Push helpers                                                              */
/* ------------------------------------------------------------------------- */

int sensor_svc_temperature_notify(const uint8_t *data, uint16_t len)
{
	int err;

	err = sensor_svc_temperature_set(data, len);
	if (err) {
		return err;
	}

	return bt_gatt_notify_uuid(NULL, SENSOR_SVC_TEMPERATURE_UUID, NULL,
				   sensor_svc_temperature_value, len);
}

static struct bt_gatt_indicate_params sensor_svc_humidity_ind_params;

int sensor_svc_humidity_indicate(const uint8_t *data, uint16_t len)
{
	int err;

	err = sensor_svc_humidity_set(data, len);
	if (err) {
		return err;
	}

	sensor_svc_humidity_ind_params.uuid = SENSOR_SVC_HUMIDITY_UUID;
	sensor_svc_humidity_ind_params.attr = NULL;
	sensor_svc_humidity_ind_params.data = sensor_svc_humidity_value;
	sensor_svc_humidity_ind_params.len = len;

	return bt_gatt_indicate(NULL, &sensor_svc_humidity_ind_params);
}

/* ------------------------------------------------------------------------- */
/* Service declaration                                                       */
/* ------------------------------------------------------------------------- */

/* clang-format off */
BT_GATT_SERVICE_DEFINE(sensor_svc,
	BT_GATT_PRIMARY_SERVICE(SENSOR_SVC_UUID),

	/* temperature: read, notify */
	BT_GATT_CHARACTERISTIC(SENSOR_SVC_TEMPERATURE_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_NOTIFY,
			       BT_GATT_PERM_READ,
			       sensor_svc_temperature_read,
			       NULL,
			       sensor_svc_temperature_value),
	BT_GATT_CUD("Temperature, 0.01 degC", BT_GATT_PERM_READ),
	BT_GATT_CPF(&sensor_svc_temperature_cpf),
	BT_GATT_CCC(sensor_svc_temperature_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* humidity: read, indicate */
	BT_GATT_CHARACTERISTIC(SENSOR_SVC_HUMIDITY_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_INDICATE,
			       BT_GATT_PERM_READ,
			       sensor_svc_humidity_read,
			       NULL,
			       sensor_svc_humidity_value),
	BT_GATT_CCC(sensor_svc_humidity_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* sampling_rate: read, write */
	BT_GATT_CHARACTERISTIC(SENSOR_SVC_SAMPLING_RATE_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE,
			       sensor_svc_sampling_rate_read,
			       sensor_svc_sampling_rate_write,
			       sensor_svc_sampling_rate_value),
);
/* clang-format on */
