#!/usr/bin/env bash
# Auto-generated by ble-gatt-generator; do not edit.
#
# Two-device BabbleSim self-test for the gatt_gen_secure profile.
# Device 1 runs the generated GATT services, device 0 connects and verifies
# them (discovery, reads, write/read-back, notifications/indications).
#
# Requires:
#   - ZEPHYR_BASE pointing at a Zephyr tree
#   - a compiled BabbleSim at ${ZEPHYR_BASE}/../tools/bsim (or BSIM_OUT_PATH)
#   - west on PATH when the test binary needs (re)building
set -euo pipefail

: "${ZEPHYR_BASE:?ZEPHYR_BASE is required}"
BSIM_OUT_PATH="${BSIM_OUT_PATH:-${ZEPHYR_BASE}/../tools/bsim}"

BOARD="nrf52_bsim/native"
exe_name="bs_nrf52_bsim_native_gatt_gen_gatt_gen_secure_selftest"
self_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ "${1:-}" = "--rebuild" ] || [ ! -f "${BSIM_OUT_PATH}/bin/${exe_name}" ]; then
	echo "Building ${exe_name} ..."
	west build -p always -b "${BOARD}" -d "${self_dir}/build" "${self_dir}"
	cp "${self_dir}/build/zephyr/zephyr.exe" "${BSIM_OUT_PATH}/bin/${exe_name}"
fi

source "${ZEPHYR_BASE}/tests/bsim/sh_common.source"

simulation_id="gatt_gen_gatt_gen_secure"

cd "${BSIM_OUT_PATH}/bin"

Execute "./${exe_name}" -v=2 -s="${simulation_id}" -d=0 \
	-testid=central -RealEncryption=1

Execute "./${exe_name}" -v=2 -s="${simulation_id}" -d=1 \
	-testid=peripheral -RealEncryption=1

Execute ./bs_2G4_phy_v1 -v=2 -s="${simulation_id}" -D=2 -sim_length=60e6

wait_for_background_jobs
