/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_notify GATT service implementation (notify_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit. Put application logic in
 *  main.c or your own sources and call the public helpers declared in
 *  notify_svc_service.h.
 */

#include <errno.h>
#include <stdint.h>
#include <string.h>

#include <zephyr/kernel.h>
#include <zephyr/sys/printk.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>

#include "notify_svc_service.h"

/* ------------------------------------------------------------------------- */
/* Characteristic value storage                                              */
/* ------------------------------------------------------------------------- */

static uint8_t notify_svc_button_value[NOTIFY_SVC_BUTTON_SIZE];
static K_MUTEX_DEFINE(notify_svc_button_lock);
static uint8_t notify_svc_led_value[NOTIFY_SVC_LED_SIZE];
static K_MUTEX_DEFINE(notify_svc_led_lock);

/* ------------------------------------------------------------------------- */
/* Static descriptor payloads                                                */
/* ------------------------------------------------------------------------- */

static const struct bt_gatt_cpf notify_svc_button_cpf = {
	.format = 1,
	.exponent = 0,
	.unit = 0,
	.name_space = 1,
	.description = 0,
};
static const struct bt_gatt_cep notify_svc_led_cep = {
	.properties = BT_GATT_CEP_RELIABLE_WRITE,
};

/* ------------------------------------------------------------------------- */
/* Thread-safe accessors                                                     */
/* ------------------------------------------------------------------------- */

int notify_svc_button_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(notify_svc_button_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&notify_svc_button_lock, K_FOREVER);
	memcpy(notify_svc_button_value, data, len);
	k_mutex_unlock(&notify_svc_button_lock);

	return 0;
}

int notify_svc_button_get(uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(notify_svc_button_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&notify_svc_button_lock, K_FOREVER);
	memcpy(data, notify_svc_button_value, len);
	k_mutex_unlock(&notify_svc_button_lock);

	return 0;
}

int notify_svc_led_set(const uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(notify_svc_led_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&notify_svc_led_lock, K_FOREVER);
	memcpy(notify_svc_led_value, data, len);
	k_mutex_unlock(&notify_svc_led_lock);

	return 0;
}

int notify_svc_led_get(uint8_t *data, uint16_t len)
{
	if (data == NULL || len > sizeof(notify_svc_led_value)) {
		return -EINVAL;
	}

	k_mutex_lock(&notify_svc_led_lock, K_FOREVER);
	memcpy(data, notify_svc_led_value, len);
	k_mutex_unlock(&notify_svc_led_lock);

	return 0;
}

/* ------------------------------------------------------------------------- */
/* GATT attribute callbacks                                                  */
/* ------------------------------------------------------------------------- */

static ssize_t notify_svc_button_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				      void *buf, uint16_t len, uint16_t offset)
{
	ssize_t ret;

	k_mutex_lock(&notify_svc_button_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, notify_svc_button_value,
				sizeof(notify_svc_button_value));
	k_mutex_unlock(&notify_svc_button_lock);

	return ret;
}

static void notify_svc_button_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	ARG_UNUSED(attr);

	printk("button notifications %s\n", value == BT_GATT_CCC_NOTIFY ? "enabled" : "disabled");
}

static ssize_t notify_svc_led_read(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf,
				   uint16_t len, uint16_t offset)
{
	ssize_t ret;

	k_mutex_lock(&notify_svc_led_lock, K_FOREVER);
	ret = bt_gatt_attr_read(conn, attr, buf, len, offset, notify_svc_led_value,
				sizeof(notify_svc_led_value));
	k_mutex_unlock(&notify_svc_led_lock);

	return ret;
}

static ssize_t notify_svc_led_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				    const void *buf, uint16_t len, uint16_t offset, uint8_t flags)
{
	ARG_UNUSED(conn);
	ARG_UNUSED(attr);

	if (offset + len > sizeof(notify_svc_led_value)) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	/* Prepare writes only validate; the value is committed on execute. */
	if (flags & BT_GATT_WRITE_FLAG_PREPARE) {
		return 0;
	}

	k_mutex_lock(&notify_svc_led_lock, K_FOREVER);
	memcpy(notify_svc_led_value + offset, buf, len);
	k_mutex_unlock(&notify_svc_led_lock);

	notify_svc_led_on_write(notify_svc_led_value, sizeof(notify_svc_led_value));

	return len;
}

/* ------------------------------------------------------------------------- */
/* Application hooks (weak defaults; override in your own sources)           */
/* ------------------------------------------------------------------------- */

__weak void notify_svc_led_on_write(const uint8_t *data, uint16_t len)
{
	ARG_UNUSED(data);
	ARG_UNUSED(len);
}

/* ------------------------------------------------------------------------- */
/* Push helpers                                                              */
/* ------------------------------------------------------------------------- */

int notify_svc_button_notify(const uint8_t *data, uint16_t len)
{
	int err;

	err = notify_svc_button_set(data, len);
	if (err) {
		return err;
	}

	return bt_gatt_notify_uuid(NULL, NOTIFY_SVC_BUTTON_UUID, NULL, notify_svc_button_value,
				   len);
}

/* ------------------------------------------------------------------------- */
/* Service declaration                                                       */
/* ------------------------------------------------------------------------- */

/* clang-format off */
BT_GATT_SERVICE_DEFINE(notify_svc,
	BT_GATT_PRIMARY_SERVICE(NOTIFY_SVC_UUID),

	/* button: read, notify */
	BT_GATT_CHARACTERISTIC(NOTIFY_SVC_BUTTON_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_NOTIFY,
			       BT_GATT_PERM_READ,
			       notify_svc_button_read,
			       NULL,
			       notify_svc_button_value),
	BT_GATT_CUD("Button state", BT_GATT_PERM_READ),
	BT_GATT_CPF(&notify_svc_button_cpf),
	BT_GATT_CCC(notify_svc_button_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),

	/* led: read, write, extended_properties */
	BT_GATT_CHARACTERISTIC(NOTIFY_SVC_LED_UUID,
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE | BT_GATT_CHRC_EXT_PROP,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE | BT_GATT_PERM_PREPARE_WRITE,
			       notify_svc_led_read,
			       notify_svc_led_write,
			       notify_svc_led_value),
	BT_GATT_CUD("LED control", BT_GATT_PERM_READ),
	BT_GATT_CEP(&notify_svc_led_cep),
);
/* clang-format on */
