/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_notify GATT service public API (notify_svc).
 *
 *  Auto-generated by ble-gatt-generator; do not edit.
 */

#ifndef BLE_GATT_GENERATOR_NOTIFY_SVC_H_
#define BLE_GATT_GENERATOR_NOTIFY_SVC_H_

#include <stdint.h>

#include <zephyr/bluetooth/uuid.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @defgroup notify_svc notify_svc service
 *  @brief Generated helpers for the notify_svc GATT service.
 *  @{
 */

/* Service and characteristic UUIDs. */
#define NOTIFY_SVC_UUID                                                                            \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef0))
#define NOTIFY_SVC_BUTTON_UUID                                                                     \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef1))
#define NOTIFY_SVC_LED_UUID                                                                        \
	BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef2))

/* Characteristic value sizes in bytes. */
#define NOTIFY_SVC_BUTTON_SIZE 1
#define NOTIFY_SVC_LED_SIZE    1

/** @brief Set the button characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              NOTIFY_SVC_BUTTON_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int notify_svc_button_set(const uint8_t *data, uint16_t len);

/** @brief Get the button characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              NOTIFY_SVC_BUTTON_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int notify_svc_button_get(uint8_t *data, uint16_t len);

/** @brief Update and notify the button characteristic.
 *
 *  @param data Pointer to the new value.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success, or a negative error code (see bt_gatt_notify_uuid()).
 */
int notify_svc_button_notify(const uint8_t *data, uint16_t len);

/** @brief Set the led characteristic value.
 *
 *  Thread-safe when @c thread_safe is enabled for this characteristic.
 *
 *  @param data Pointer to the data to copy into the value buffer.
 *  @param len  Number of bytes to copy; must not exceed
 *              NOTIFY_SVC_LED_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int notify_svc_led_set(const uint8_t *data, uint16_t len);

/** @brief Get the led characteristic value.
 *
 *  @param data Buffer to receive the value.
 *  @param len  Number of bytes to copy; must not exceed
 *              NOTIFY_SVC_LED_SIZE.
 *
 *  @retval 0 on success.
 *  @retval -EINVAL if @p data is NULL or @p len is too large.
 */
int notify_svc_led_get(uint8_t *data, uint16_t len);

/** @brief Application hook called after a peer writes led.
 *
 *  Defined as a weak no-op in the generated source. Define this function in
 *  your own code to react to remote writes; it is called outside the value
 *  lock from the Bluetooth RX context, so keep it short.
 *
 *  @param data Pointer to the (already updated) value buffer.
 *  @param len  Size of the value buffer in bytes.
 */
void notify_svc_led_on_write(const uint8_t *data, uint16_t len);

/** @} */

#ifdef __cplusplus
}
#endif

#endif /* BLE_GATT_GENERATOR_NOTIFY_SVC_H_ */
