/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_notify GATT service implementation.
 *
 *  Auto-generated by gatt-gen; do not edit.
 */

#include <stdint.h>
#include <string.h>
#include <zephyr/toolchain.h>
#include <zephyr/sys/printk.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>

#include "notify_svc_service.h"

/* Characteristic value buffers */
static uint8_t notify_svc_button_value[1];
static uint8_t notify_svc_led_value[1];

/* Characteristic presentation format and extended properties data */
static struct bt_gatt_cpf notify_svc_button_cpf = {
	.format = 1,
	.exponent = 0,
	.unit = 0,
	.name_space = 1,
	.description = 0,
};
static struct bt_gatt_cep notify_svc_led_cep = {
	.properties = BT_GATT_CEP_RELIABLE_WRITE,
};

/* Characteristic callbacks */
static ssize_t notify_svc_button_read(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				      void *buf, uint16_t len, uint16_t offset)
{
	uint8_t *value = (uint8_t *)attr->user_data;

	return bt_gatt_attr_read(conn, attr, buf, len, offset, value, 1);
}
static void notify_svc_button_ccc_cfg_changed(const struct bt_gatt_attr *attr, uint16_t value)
{
	ARG_UNUSED(attr);

	if (value == BT_GATT_CCC_NOTIFY) {
		printk("button notifications enabled\n");
	} else if (value == 0) {
		printk("button notifications disabled\n");
	}
}
static ssize_t notify_svc_led_read(struct bt_conn *conn, const struct bt_gatt_attr *attr, void *buf,
				   uint16_t len, uint16_t offset)
{
	uint8_t *value = (uint8_t *)attr->user_data;

	return bt_gatt_attr_read(conn, attr, buf, len, offset, value, 1);
}
static ssize_t notify_svc_led_write(struct bt_conn *conn, const struct bt_gatt_attr *attr,
				    const void *buf, uint16_t len, uint16_t offset, uint8_t flags)
{
	uint8_t *value = (uint8_t *)attr->user_data;

	if (offset + len > 1) {
		return BT_GATT_ERR(BT_ATT_ERR_INVALID_OFFSET);
	}

	memcpy(value + offset, buf, len);

	return len;
}

/* Public API */
int notify_svc_button_notify(const uint8_t *data, uint16_t len)
{
	return bt_gatt_notify_uuid(NULL,
				   BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(
					   0x12345678, 0x1234, 0x5678, 0x1234, 0x56789abcdef1)),
				   NULL, data, len);
}

/* Service declaration */
BT_GATT_SERVICE_DEFINE(
	notify_svc,
	BT_GATT_PRIMARY_SERVICE(BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678,
								       0x1234, 0x56789abcdef0))),
	BT_GATT_CHARACTERISTIC(BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678,
								      0x1234, 0x56789abcdef1)),
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_NOTIFY, BT_GATT_PERM_READ,
			       notify_svc_button_read, NULL, notify_svc_button_value),
	BT_GATT_CUD("Button state", BT_GATT_PERM_READ), BT_GATT_CPF(&notify_svc_button_cpf),
	BT_GATT_CCC(notify_svc_button_ccc_cfg_changed, BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),
	BT_GATT_CHARACTERISTIC(BT_UUID_DECLARE_128(BT_UUID_128_ENCODE(0x12345678, 0x1234, 0x5678,
								      0x1234, 0x56789abcdef2)),
			       BT_GATT_CHRC_READ | BT_GATT_CHRC_WRITE,
			       BT_GATT_PERM_READ | BT_GATT_PERM_WRITE, notify_svc_led_read,
			       notify_svc_led_write, notify_svc_led_value),
	BT_GATT_CUD("LED control", BT_GATT_PERM_READ), BT_GATT_CEP(&notify_svc_led_cep));
