/*
 * Copyright (c) 2026 Ankit Modi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 *  @brief gatt_gen_notify GATT service definition.
 *
 *  Auto-generated by gatt-gen; do not edit.
 */

#ifndef ZEPHYR_GATT_GEN_NOTIFY_SVC_H_
#define ZEPHYR_GATT_GEN_NOTIFY_SVC_H_

#include <stdint.h>
#include <zephyr/bluetooth/gatt.h>

/** @brief Send a notification for the button characteristic.
 *
 *  @param data Pointer to the data to notify.
 *  @param len  Length of the data in bytes.
 *
 *  @return 0 on success or a negative error code.
 */
int notify_svc_button_notify(const uint8_t *data, uint16_t len);

#endif /* ZEPHYR_GATT_GEN_NOTIFY_SVC_H_ */
